/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.proyectofinal.frames;

import com.proyectofinal.clases.Consulta;
import com.proyectofinal.clases.Hash;
import com.proyectofinal.clases.empleado;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Manuel
 */
public class crearCuentaEmpleado extends javax.swing.JFrame {

    String pass;
    String tipoEmpleado_;
        String rutaImg = null;
        
    
    /**
     * Creates new form crearCuentaEmpleado
     */
    public crearCuentaEmpleado() {
        initComponents();
            setearIconos();
                validarCorreo();
                    cerrar();
    }

    protected void validarCorreo(){
        KeyListener listener = new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {//tipo de tecla
            }

            @Override
            public void keyPressed(KeyEvent e) {//se presiona la tecla
            }

            @Override
            public void keyReleased(KeyEvent e) {// se suelta la tecla
                if(e.getKeyChar()=='\n'){//si se presiona un enter en la caja de texto del email validarlo
                    if(validarEmail(jtxtEmail.getText())==false){
                        Icon registroExitoso = new ImageIcon(getClass().getResource("/04_accounts/emailIncorrect.png"));
                        JOptionPane.showMessageDialog(null, "FORMATO DE CORREO ELECTRÓNICO NO VÁLIDO", "MENSAJE", JOptionPane.OK_OPTION, registroExitoso);
                    }
                }
            }
        };
        jtxtEmail.addKeyListener(listener);
    }
    
    
    public boolean validarEmail(String email){
            //para validar, en éste caso, una cadena de texto con las especificaciones indicadas.
            Pattern pattern = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"+"[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
            //matcher es un comparador, en este caso comparamos el pattern con el email que enviaremos.
            Matcher matcher_ = pattern.matcher(email);
            return matcher_.find();
    }  
    
    class jPanelGradient extends JPanel{
        
        @Override
        protected void paintComponent(Graphics g){
            Graphics2D g2d = (Graphics2D) g;
                int width = getWidth();
                int height = getHeight();
                    Color colorUno = new Color(0, 120, 174);
                    Color colorDos = new Color(185, 238, 226);
                        GradientPaint gp = new GradientPaint(0,0,colorUno,180,height,colorDos);
                            g2d.setPaint(gp);
                            g2d.fillRect(0, 0, width, height);
                
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCreateAccount = new jPanelGradient();
        jtxtUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtxtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtApellido = new javax.swing.JTextField();
        jtxtEmail = new javax.swing.JTextField();
        jtxtPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jcmTipoEmpleado = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jbtnFoto = new javax.swing.JButton();
        jcbMostrar = new javax.swing.JCheckBox();
        jtxtConfirmPassword = new javax.swing.JPasswordField();
        jbtnRegistrarEmpleado = new javax.swing.JButton();
        lblFotoElegida = new javax.swing.JLabel();
        jbtnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DOMINO´S PIZZA");
        setMaximumSize(new java.awt.Dimension(900, 500));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setResizable(false);

        jpCreateAccount.setMaximumSize(new java.awt.Dimension(900, 500));
        jpCreateAccount.setMinimumSize(new java.awt.Dimension(900, 500));
        jpCreateAccount.setPreferredSize(new java.awt.Dimension(900, 500));

        jtxtUsuario.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jtxtUsuario.setForeground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("USUARIO");

        jtxtNombre.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jtxtNombre.setForeground(new java.awt.Color(51, 51, 51));
        jtxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNombreActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("NOMBRE");

        jtxtApellido.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jtxtApellido.setForeground(new java.awt.Color(51, 51, 51));

        jtxtEmail.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jtxtEmail.setForeground(new java.awt.Color(51, 51, 51));

        jtxtPassword.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jtxtPassword.setForeground(new java.awt.Color(51, 51, 51));
        jtxtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPasswordActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("APELLIDO");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("E-MAIL");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("CONTRASEÑA");

        jcmTipoEmpleado.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jcmTipoEmpleado.setForeground(new java.awt.Color(51, 51, 51));
        jcmTipoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CAJERO", "GERENTE" }));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("CONTRASEÑA");

        jbtnFoto.setBackground(new java.awt.Color(0, 102, 102));
        jbtnFoto.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbtnFoto.setForeground(new java.awt.Color(255, 255, 255));
        jbtnFoto.setText("SUBIR");
        jbtnFoto.setBorder(null);
        jbtnFoto.setBorderPainted(false);
        jbtnFoto.setFocusPainted(false);
        jbtnFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnFotoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnFotoMouseExited(evt);
            }
        });
        jbtnFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFotoActionPerformed(evt);
            }
        });

        jcbMostrar.setBackground(new java.awt.Color(154, 218, 217));
        jcbMostrar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jcbMostrar.setForeground(new java.awt.Color(51, 51, 51));
        jcbMostrar.setText("MOSTRAR");
        jcbMostrar.setBorder(null);
        jcbMostrar.setFocusPainted(false);
        jcbMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMostrarActionPerformed(evt);
            }
        });

        jtxtConfirmPassword.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jtxtConfirmPassword.setForeground(new java.awt.Color(51, 51, 51));

        jbtnRegistrarEmpleado.setBackground(new java.awt.Color(0, 120, 174));
        jbtnRegistrarEmpleado.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jbtnRegistrarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        jbtnRegistrarEmpleado.setText("REGISTRAR");
        jbtnRegistrarEmpleado.setBorder(null);
        jbtnRegistrarEmpleado.setBorderPainted(false);
        jbtnRegistrarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnRegistrarEmpleado.setFocusPainted(false);
        jbtnRegistrarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnRegistrarEmpleadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnRegistrarEmpleadoMouseExited(evt);
            }
        });
        jbtnRegistrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegistrarEmpleadoActionPerformed(evt);
            }
        });

        lblFotoElegida.setBackground(new java.awt.Color(102, 102, 102));
        lblFotoElegida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/04_accounts/photoProfile.png"))); // NOI18N

        jbtnVolver.setBackground(new java.awt.Color(161, 223, 219));
        jbtnVolver.setBorder(null);
        jbtnVolver.setBorderPainted(false);
        jbtnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnVolver.setFocusPainted(false);
        jbtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCreateAccountLayout = new javax.swing.GroupLayout(jpCreateAccount);
        jpCreateAccount.setLayout(jpCreateAccountLayout);
        jpCreateAccountLayout.setHorizontalGroup(
            jpCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCreateAccountLayout.createSequentialGroup()
                .addGroup(jpCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCreateAccountLayout.createSequentialGroup()
                        .addGroup(jpCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpCreateAccountLayout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addGroup(jpCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jpCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxtApellido)
                                    .addComponent(jtxtUsuario)
                                    .addComponent(jtxtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                                    .addComponent(jtxtEmail)))
                            .addGroup(jpCreateAccountLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(jpCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpCreateAccountLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCreateAccountLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addGroup(jpCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jcbMostrar)
                                            .addComponent(jtxtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(jpCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpCreateAccountLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jpCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jbtnFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcmTipoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCreateAccountLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(lblFotoElegida, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jpCreateAccountLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(208, 208, 208)
                        .addComponent(jbtnRegistrarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jpCreateAccountLayout.setVerticalGroup(
            jpCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCreateAccountLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jpCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCreateAccountLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblFotoElegida, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnFoto))
                    .addGroup(jpCreateAccountLayout.createSequentialGroup()
                        .addGroup(jpCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jpCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jcmTipoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbMostrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jbtnRegistrarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCreateAccountLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCreateAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCreateAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnRegistrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegistrarEmpleadoActionPerformed
        try {
        if(hayCamposVacios()!=true){      
                    empleado emp = new empleado();
                    Consulta mysql = new Consulta();

                    pass = new String(jtxtPassword.getPassword());
                    String passConfirm = new String(jtxtConfirmPassword.getPassword());

                        if(pass.equals(passConfirm)==true){
                                if(mysql.validarExistenciaUsuario(jtxtUsuario.getText())>0){//SI ES MAYOR A CERO O EN TODO CASO IGUAL A UNO EL USUARIO YE
                                    Icon usuarioRegistrado= new ImageIcon(getClass().getResource("/04_accounts/userAlreadyRegistered.png"));
                                    JOptionPane.showMessageDialog(null, "EL USUARIO ESPECIFICADO YA ESTÁ REGISTRADO", "MENSAJE", JOptionPane.OK_OPTION,usuarioRegistrado);
                                }else{ //EL USUARIO NO EXISTE Y POR ENDE PODEMOS REGISTRARLO.
                                        if(mysql.validarEmail(jtxtEmail.getText())){ 
                                                pass = Hash.sha1(pass);
                                                emp = setDatosInObject(new empleado());
                                                    if(mysql.registrarUsuario(emp)==true){
                                                        Icon registroExitoso = new ImageIcon(getClass().getResource("/03_mensajes/succesful.png"));
                                                        JOptionPane.showMessageDialog(null, "USUARIO REGISTRADO CON ÉXITO", "MENSAJE", JOptionPane.OK_OPTION, registroExitoso);
                                                            this.dispose();
                                                                jfLoginOrCreateAcount loca = new jfLoginOrCreateAcount();
                                                                    loca.setVisible(true); 
                                                    }else{
                                                        throw new SQLException(); //línea 208
                                                    }
                                        }else{
                                             Icon registroExitoso = new ImageIcon(getClass().getResource("/04_accounts/emailIncorrect.png"));
                                             JOptionPane.showMessageDialog(null, "FORMATO DE CORREO ELECTRÓNICO NO VÁLIDO", "MENSAJE", JOptionPane.OK_OPTION, registroExitoso);
                                        }
                                }
                        }else{
                            Icon contraMala;
                            contraMala = new ImageIcon(getClass().getResource("/03_mensajes/contraIncorrecta.png"));
                            JOptionPane.showMessageDialog(null, "LAS CONTRASEÑAS NO COINCIDEN", "ATENCIÓN",JOptionPane.OK_OPTION, contraMala);
                        }
                }else{
                    Icon camposVacios;
                    camposVacios =  new ImageIcon(getClass().getResource("/04_accounts/camposVacios.png"));
                    JOptionPane.showMessageDialog(null, "NO PUEDES DEJAR CAMPOS VACÍOS", "MENSAJE", JOptionPane.OK_OPTION,camposVacios);
                }
        } catch (HeadlessException | SQLException e) {
                Icon algunErrorsito;
                    algunErrorsito = new ImageIcon(getClass().getResource("/03_mensajes/errorEnRegistro.png"));
                        JOptionPane.showMessageDialog(null, "ERROR DE REGISTRO, VERIFICA LA EXTENSIÓN DE LA FOTOGRAFÍA", "ATENCIÓN",JOptionPane.OK_OPTION, algunErrorsito);
                            System.out.println(e.getMessage());
         } catch (FileNotFoundException ex) {
            Logger.getLogger(crearCuentaEmpleado.class.getName()).log(Level.SEVERE, null, ex);
            Icon algunErrorsito;
                    algunErrorsito = new ImageIcon(getClass().getResource("/03_mensajes/errorEnRegistro.png"));
                        JOptionPane.showMessageDialog(null, "ERORR AL BUSCAR EL PATH DE LA FOTOGRAFÍA", "ATENCIÓN",JOptionPane.OK_OPTION, algunErrorsito);
                            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jbtnRegistrarEmpleadoActionPerformed
 
    public void setearIconos(){
        jbtnVolver.setIcon(setIconoBtn("/02_clasificacion_menu/05.png",jbtnVolver));
            this.setIconImage(new ImageIcon(getClass().getResource("/00_jf_principal/idm.png")).getImage());
    }
    
      public Icon setIconoBtn(String url, JButton btn){
        ImageIcon imgIcon = new ImageIcon(getClass().getResource(url));
            int widthBtn = btn.getWidth();
                int heightBtn = btn.getHeight();
        
                    ImageIcon iconoBtn = new ImageIcon(imgIcon.getImage().getScaledInstance(widthBtn, heightBtn, Image.SCALE_DEFAULT));
                        return iconoBtn;
    }
    
    public boolean hayCamposVacios(){
            if(jtxtUsuario.getText().equals("")||jtxtNombre.getText().equals("")||jtxtApellido.getText().equals("")||jtxtEmail.getText().equals("")||jtxtPassword.getPassword().equals("")||jtxtConfirmPassword.getPassword().equals("")||(rutaImg == null)){
                return true;
            }
        return false;
    }
    
    private void jcbMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMostrarActionPerformed
        if(jcbMostrar.isSelected()){
            jtxtConfirmPassword.setEchoChar((char)0);
        }else{
            jtxtConfirmPassword.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_jcbMostrarActionPerformed

    private void jtxtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPasswordActionPerformed

    private void jtxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombreActionPerformed

    private void jbtnRegistrarEmpleadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnRegistrarEmpleadoMouseEntered
        jbtnRegistrarEmpleado.setBackground(new Color(0,120,174));
        jbtnRegistrarEmpleado.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_jbtnRegistrarEmpleadoMouseEntered

    private void jbtnRegistrarEmpleadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnRegistrarEmpleadoMouseExited
        jbtnRegistrarEmpleado.setBackground(new Color(255,255,255));
        jbtnRegistrarEmpleado.setForeground(new Color(0,120,174));
    }//GEN-LAST:event_jbtnRegistrarEmpleadoMouseExited

    private void jbtnFotoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnFotoMouseExited
        jbtnFoto.setBackground(new Color(0,102,102));
        jbtnFoto.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_jbtnFotoMouseExited

    private void jbtnFotoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnFotoMouseEntered
        jbtnFoto.setBackground(new Color(255,255,255));
        jbtnFoto.setForeground(new Color(0,102,102));
    }//GEN-LAST:event_jbtnFotoMouseEntered

    private void jbtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVolverActionPerformed
        backFromThis();
    }//GEN-LAST:event_jbtnVolverActionPerformed

    private void jbtnFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFotoActionPerformed
        
        JFileChooser jfc = new JFileChooser();
            jfc.setFileSelectionMode(JFileChooser.FILES_ONLY);
                FileNameExtensionFilter filtrarArchivos = new FileNameExtensionFilter("*.JPG", "jpg");
                    jfc.setFileFilter(filtrarArchivos);  
        
                        int fileSelected = jfc.showOpenDialog(this);
                            if(fileSelected == JFileChooser.APPROVE_OPTION){
                                rutaImg = jfc.getSelectedFile().getAbsolutePath();
                                        lblFotoElegida.setIcon(new ImageIcon(rutaImg));
                            }
    }//GEN-LAST:event_jbtnFotoActionPerformed

    public void cerrar(){
    
        try {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e){ //WindowEvent: import java.awt.event.WindowEvent;
                      confirmarCerrarVentana();
                }
            });
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
   
    public void backFromThis(){
        
        Icon question;
        question = new ImageIcon(getClass().getResource("/00_jf_principal/question.png"));
        
        int valor = JOptionPane.showConfirmDialog(null, "¿REALMENTE QUIERES REGRESAR Y CERRAR LA VENTANA?", "ATENCIÓN", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE,question);
        if(valor == JOptionPane.YES_OPTION){
            this.dispose(); 
                jfLoginOrCreateAcount app1 = new jfLoginOrCreateAcount();
                    app1.setVisible(true);
        } 
        
    }
   
    public void confirmarCerrarVentana(){
        backFromThis();
    }
    
    public empleado setDatosInObject(empleado emp){
        emp.setUsuario(jtxtUsuario.getText());
            emp.setNombre(jtxtNombre.getText());
                emp.setApellido(jtxtApellido.getText());
                    emp.setCorreo(jtxtEmail.getText());
                        emp.setPassword(pass);
                            if(jcmTipoEmpleado.getSelectedItem().equals("CAJERO")){
                                tipoEmpleado_ = "CAJERO";
                            }else{
                                tipoEmpleado_ = "GERENTE";
                            }
                            emp.setTipoEmpleado(tipoEmpleado_);
                            emp.setRutaFoto(rutaImg); 
                                return emp;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crearCuentaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crearCuentaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crearCuentaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crearCuentaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crearCuentaEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbtnFoto;
    private javax.swing.JButton jbtnRegistrarEmpleado;
    private javax.swing.JButton jbtnVolver;
    private javax.swing.JCheckBox jcbMostrar;
    private javax.swing.JComboBox<String> jcmTipoEmpleado;
    private javax.swing.JPanel jpCreateAccount;
    private javax.swing.JTextField jtxtApellido;
    private javax.swing.JPasswordField jtxtConfirmPassword;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JPasswordField jtxtPassword;
    private javax.swing.JTextField jtxtUsuario;
    private javax.swing.JLabel lblFotoElegida;
    // End of variables declaration//GEN-END:variables
}
