/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.proyectofinal.frames;

import com.proyectofinal.clases.cliente;
import com.proyectofinal.clases.conection;
import com.proyectofinal.clases.empleado;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Manuel
 */
public final class jfClientes extends javax.swing.JFrame {

    empleado emp;
    cliente client =null;
    
    /**
     * Creates new form jfClientes
     */
    public jfClientes() {
        initComponents();
    }
    
    public jfClientes(empleado emp) {
        this.emp = emp;
            initComponents();
                cerrar();
                    setImgComponents();
    }

    public void setImgComponents(){
        this.setIconImage(new ImageIcon(getClass().getResource("/00_jf_principal/idm.png")).getImage());
            jbtnVolver.setIcon(setIconoBtn("/06_mesasClientes/05.png",jbtnVolver));
    }
    
       public Icon setIconoBtn(String url, JButton btn){
    
        //jbtnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizza.png")));
        ImageIcon imgIcon = new ImageIcon(getClass().getResource(url));
            int widthBtn = btn.getWidth();
                int heightBtn = btn.getHeight();
        
                    ImageIcon iconoBtn = new ImageIcon(imgIcon.getImage().getScaledInstance(widthBtn, heightBtn, Image.SCALE_DEFAULT));
                        return iconoBtn;
    }
    
    public void cerrar(){
        try {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e){ //WindowEvent: import java.awt.event.WindowEvent;
                      confirmarCerrarVentana();
                }
            });
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void confirmarCerrarVentana(){
        Icon question;
        question = new ImageIcon(getClass().getResource("/00_jf_principal/question.png"));
        
        int valor = JOptionPane.showConfirmDialog(null, "¿REALMENTE QUIERES CERRAR LA VENTANA?", "ATENCIÓN", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE,question);
        if(valor == JOptionPane.YES_OPTION){
            jfRegistrarActualizarEliminar rae = new jfRegistrarActualizarEliminar(emp);
                this.dispose();
                    rae.setVisible(true);
        }else{
            this.setVisible(true);
        }  
    }
    
    class jPanelGradient extends JPanel{
        
        @Override
        protected void paintComponent(Graphics g){
            Graphics2D g2d = (Graphics2D) g;
                int width = getWidth();
                int height = getHeight();
                    Color colorUno = new Color(0, 120, 174);
                    Color colorDos = new Color(185, 238, 226);
                        GradientPaint gp = new GradientPaint(0,0,colorUno,180,height,colorDos);
                            g2d.setPaint(gp);
                            g2d.fillRect(0, 0, width, height);
                
        }
    }
    
    class jPanelGradient2 extends JPanel{  
            @Override
            protected void paintComponent(Graphics g){
                Graphics2D g2d = (Graphics2D) g;
                    int width = getWidth();
                    int height = getHeight();                
                        Color colorUno = new Color(255,255,255);
                        Color colorDos = new Color(187,187,187);
                            GradientPaint gp = new GradientPaint(0,0,colorUno,180,height,colorDos);
                                g2d.setPaint(gp);
                                g2d.fillRect(0, 0, width, height);
            }
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelPerfilUsuario = new jPanelGradient();
        jbtnVolver = new javax.swing.JButton();
        jpEncabezado = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jpanelDatosATraer = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jpanelDatosATraer1 = new jPanelGradient2();
        jtxtNit = new javax.swing.JTextField();
        jtxtNombre = new javax.swing.JTextField();
        jtxtApellido = new javax.swing.JTextField();
        jtxtCorreo = new javax.swing.JTextField();
        jbtnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DOMINO´S PIZZA");

        jpanelPerfilUsuario.setMaximumSize(new java.awt.Dimension(900, 500));
        jpanelPerfilUsuario.setMinimumSize(new java.awt.Dimension(900, 500));
        jpanelPerfilUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnVolver.setBackground(new java.awt.Color(161, 223, 219));
        jbtnVolver.setBorder(null);
        jbtnVolver.setBorderPainted(false);
        jbtnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnVolver.setFocusPainted(false);
        jbtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVolverActionPerformed(evt);
            }
        });
        jpanelPerfilUsuario.add(jbtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 80, 75));

        jpEncabezado.setBackground(new java.awt.Color(0, 100, 145));

        jLabel3.setBackground(new java.awt.Color(0, 100, 145));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("INGRESE LOS DATOS DEL CLIENTE");

        javax.swing.GroupLayout jpEncabezadoLayout = new javax.swing.GroupLayout(jpEncabezado);
        jpEncabezado.setLayout(jpEncabezadoLayout);
        jpEncabezadoLayout.setHorizontalGroup(
            jpEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEncabezadoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addContainerGap(467, Short.MAX_VALUE))
        );
        jpEncabezadoLayout.setVerticalGroup(
            jpEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEncabezadoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jpanelPerfilUsuario.add(jpEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 70));

        jpanelDatosATraer.setBackground(new java.awt.Color(0, 100, 145));

        jLabel4.setBackground(new java.awt.Color(0, 100, 145));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NIT");

        jLabel5.setBackground(new java.awt.Color(0, 100, 145));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NOMBRE");

        jLabel6.setBackground(new java.awt.Color(0, 100, 145));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CORREO");

        jLabel7.setBackground(new java.awt.Color(0, 100, 145));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("APELLIDO");

        javax.swing.GroupLayout jpanelDatosATraerLayout = new javax.swing.GroupLayout(jpanelDatosATraer);
        jpanelDatosATraer.setLayout(jpanelDatosATraerLayout);
        jpanelDatosATraerLayout.setHorizontalGroup(
            jpanelDatosATraerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelDatosATraerLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jpanelDatosATraerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jpanelDatosATraerLayout.setVerticalGroup(
            jpanelDatosATraerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelDatosATraerLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(27, 27, 27))
        );

        jpanelPerfilUsuario.add(jpanelDatosATraer, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 150, 240));

        jtxtNit.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jtxtNit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNitActionPerformed(evt);
            }
        });

        jtxtNombre.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jtxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNombreActionPerformed(evt);
            }
        });

        jtxtApellido.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jtxtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtApellidoActionPerformed(evt);
            }
        });

        jtxtCorreo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jtxtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCorreoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelDatosATraer1Layout = new javax.swing.GroupLayout(jpanelDatosATraer1);
        jpanelDatosATraer1.setLayout(jpanelDatosATraer1Layout);
        jpanelDatosATraer1Layout.setHorizontalGroup(
            jpanelDatosATraer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelDatosATraer1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jpanelDatosATraer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtNit, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jpanelDatosATraer1Layout.setVerticalGroup(
            jpanelDatosATraer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelDatosATraer1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jtxtNit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jtxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jpanelPerfilUsuario.add(jpanelDatosATraer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 270, 240));

        jbtnCerrarSesion.setBackground(new java.awt.Color(0, 120, 174));
        jbtnCerrarSesion.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jbtnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        jbtnCerrarSesion.setText("REGISTRAR");
        jbtnCerrarSesion.setBorder(null);
        jbtnCerrarSesion.setBorderPainted(false);
        jbtnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnCerrarSesion.setFocusPainted(false);
        jbtnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnCerrarSesionMouseExited(evt);
            }
        });
        jbtnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCerrarSesionActionPerformed(evt);
            }
        });
        jpanelPerfilUsuario.add(jbtnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpanelPerfilUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpanelPerfilUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVolverActionPerformed
        confirmarCerrarVentana();
    }//GEN-LAST:event_jbtnVolverActionPerformed

    
    
    private void jbtnCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnCerrarSesionMouseEntered
        jbtnCerrarSesion.setBackground(new Color(0,120,174));
        jbtnCerrarSesion.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_jbtnCerrarSesionMouseEntered

    private void jbtnCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnCerrarSesionMouseExited
        jbtnCerrarSesion.setBackground(new Color(255,255,255));
        jbtnCerrarSesion.setForeground(new Color(0,120,174));
    }//GEN-LAST:event_jbtnCerrarSesionMouseExited

    private void jbtnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCerrarSesionActionPerformed
            try {
                  client = new cliente();
                    client.setNIT(jtxtNit.getText());
                         client.setNombre(jtxtNombre.getText());
                             client.setApellido(jtxtApellido.getText());
                                 client.setCorreo_electronico(jtxtCorreo.getText());
                                 
                if(hayCamposVacios(client)==false){
                  
                    if(validarExistenciaCliente(client.getNIT())==0){
                        
                        if(correoValido(client.getCorreo_electronico())==true){
                            conection conectar = new conection();
                            Connection cn = conectar.getConection();
                            String query = "{CALL REGISTRAR_CLIENTE(?,?,?,?)}";
                            CallableStatement cts = cn.prepareCall(query);
                                cts.setString(1,client.getNIT());
                                cts.setString(2, client.getNombre());
                                cts.setString(3, client.getApellido());
                                cts.setString(4, client.getCorreo_electronico());
                                int res = cts.executeUpdate();

                                    if(res>0){
                                        Icon registroExitoso = new ImageIcon(getClass().getResource("/03_mensajes/succesful.png"));
                                            JOptionPane.showMessageDialog(null, "CLIENTE REGISTRADO CON ÉXITO", "MENSAJE", JOptionPane.OK_OPTION, registroExitoso);
                                                cleanInput();
                                    }else{
                                        System.out.println("resulset");
                                        cleanInput();
                                            throw new SQLException();
                                    }
                        }else{
                            Icon algunErrorsito= new ImageIcon(getClass().getResource("/03_mensajes/errorEnRegistro.png"));
                            JOptionPane.showMessageDialog(null, "EL E-MAIL INGRESADO NO ES VÁLIDO", "ATENCIÓN",JOptionPane.OK_OPTION, algunErrorsito);
                        }
                        
                    }else{
                        System.out.println("ya existe");
                         //cleanInput();
                              throw new SQLException();
                    }
                    
                    
                }else{
                    Icon algunErrorsito= new ImageIcon(getClass().getResource("/03_mensajes/errorEnRegistro.png"));
                            JOptionPane.showMessageDialog(null, "NO PUEDES DEJAR CAMPOS VACÍOS", "ATENCIÓN",JOptionPane.OK_OPTION, algunErrorsito);
                }
                
            
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            Icon algunErrorsito= new ImageIcon(getClass().getResource("/03_mensajes/errorEnRegistro.png"));
               JOptionPane.showMessageDialog(null, "VERIFICA LOS DATOS INGRESADOS, PUEDE QUE EL CLIENTE YA ESTÉ REGISTRADO", "ATENCIÓN",JOptionPane.OK_OPTION, algunErrorsito);
               
        }
              
    }//GEN-LAST:event_jbtnCerrarSesionActionPerformed

    public boolean correoValido(String email){
        Pattern pattern = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"+"[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
            Matcher matcher_ = pattern.matcher(email);
            return matcher_.find();
    }
    
    public int validarExistenciaCliente(String nitCliente){
        try {
            conection conectar = new conection();
            CallableStatement cts = null;
            Connection con = conectar.getConection();
                ResultSet rs;
                String query = "{CALL VALIDAR_CLIENTE(?)}";
                    cts = con.prepareCall(query);
                        cts.setString(1, client.getNIT());
                            rs = cts.executeQuery();
                                if(rs.next()){
                                    //si hay un registro significa que no podemos usarlo, por lo tanto
                                    return rs.getInt(1);
                                }
                                    return 1;
                        
        } catch (ClassNotFoundException | SQLException e) {
            return 1;
        }
    }
    
    public void cleanInput(){
        jtxtNit.setText(null);
            jtxtNombre.setText(null);
                jtxtApellido.setText(null);
                    jtxtCorreo.setText(null); 
    }
    
    private void jtxtNitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNitActionPerformed

    private void jtxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombreActionPerformed

    private void jtxtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtApellidoActionPerformed

    private void jtxtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCorreoActionPerformed

    public boolean hayCamposVacios(cliente client){
    
        if(client.getNIT().equals("")||client.getNombre().equals("")||client.getApellido().equals("")||client.getCorreo_electronico().equals("")){
            return true;
        }
        
        return false;
    }
    
    public void backFromThis(){
        confirmarCerrarVentana();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbtnCerrarSesion;
    private javax.swing.JButton jbtnVolver;
    private javax.swing.JPanel jpEncabezado;
    private javax.swing.JPanel jpanelDatosATraer;
    private javax.swing.JPanel jpanelDatosATraer1;
    private javax.swing.JPanel jpanelPerfilUsuario;
    private javax.swing.JTextField jtxtApellido;
    private javax.swing.JTextField jtxtCorreo;
    private javax.swing.JTextField jtxtNit;
    private javax.swing.JTextField jtxtNombre;
    // End of variables declaration//GEN-END:variables
}
