/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.proyectofinal.frames;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Manuel
 */
public class jfClasificacionMenu extends javax.swing.JFrame {

    /**
     * Creates new form jfClasificacionMenu
     */
    public jfClasificacionMenu() {
        initComponents();
        setearIconos();
    }

    class jPanelGradient extends JPanel{
        
        @Override
        protected void paintComponent(Graphics g){
            Graphics2D g2d = (Graphics2D) g;
                int width = getWidth();
                int height = getHeight();
                    Color colorUno = new Color(0, 120, 174);
                    Color colorDos = new Color(185, 238, 226);
                        GradientPaint gp = new GradientPaint(0,0,colorUno,180,height,colorDos);
                            g2d.setPaint(gp);
                            g2d.fillRect(0, 0, width, height);
                
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelCategorias = new jPanelGradient();
        jbtnPizzas = new javax.swing.JButton();
        jbtnAdicionales = new javax.swing.JButton();
        jbtnDonCalzzone = new javax.swing.JButton();
        jbtnBebidas = new javax.swing.JButton();
        jbtnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DOMINO´S PIZZA");
        setMaximumSize(new java.awt.Dimension(900, 500));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setResizable(false);

        jbtnPizzas.setBackground(new java.awt.Color(255, 255, 255));
        jbtnPizzas.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jbtnPizzas.setForeground(new java.awt.Color(0, 120, 174));
        jbtnPizzas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/02_clasificacion_menu/01.png"))); // NOI18N
        jbtnPizzas.setText("               PIZZAS");
        jbtnPizzas.setBorderPainted(false);
        jbtnPizzas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnPizzas.setFocusPainted(false);
        jbtnPizzas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jbtnPizzas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnPizzasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnPizzasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnPizzasMouseExited(evt);
            }
        });
        jbtnPizzas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPizzasActionPerformed(evt);
            }
        });

        jbtnAdicionales.setBackground(new java.awt.Color(255, 255, 255));
        jbtnAdicionales.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jbtnAdicionales.setForeground(new java.awt.Color(0, 120, 174));
        jbtnAdicionales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/02_clasificacion_menu/02.png"))); // NOI18N
        jbtnAdicionales.setText("         ADICIONALES");
        jbtnAdicionales.setBorderPainted(false);
        jbtnAdicionales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnAdicionales.setFocusPainted(false);
        jbtnAdicionales.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jbtnAdicionales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnAdicionalesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnAdicionalesMouseExited(evt);
            }
        });
        jbtnAdicionales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAdicionalesActionPerformed(evt);
            }
        });

        jbtnDonCalzzone.setBackground(new java.awt.Color(255, 255, 255));
        jbtnDonCalzzone.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jbtnDonCalzzone.setForeground(new java.awt.Color(0, 120, 174));
        jbtnDonCalzzone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/02_clasificacion_menu/03.png"))); // NOI18N
        jbtnDonCalzzone.setText("        DON CALZZONE");
        jbtnDonCalzzone.setBorderPainted(false);
        jbtnDonCalzzone.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnDonCalzzone.setFocusPainted(false);
        jbtnDonCalzzone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jbtnDonCalzzone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnDonCalzzoneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnDonCalzzoneMouseExited(evt);
            }
        });

        jbtnBebidas.setBackground(new java.awt.Color(255, 255, 255));
        jbtnBebidas.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jbtnBebidas.setForeground(new java.awt.Color(0, 120, 174));
        jbtnBebidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/02_clasificacion_menu/04.png"))); // NOI18N
        jbtnBebidas.setText("                 BEBIDAS");
        jbtnBebidas.setBorderPainted(false);
        jbtnBebidas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnBebidas.setFocusPainted(false);
        jbtnBebidas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jbtnBebidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnBebidasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnBebidasMouseExited(evt);
            }
        });

        jbtnVolver.setBackground(new java.awt.Color(185, 238, 226));
        jbtnVolver.setBorder(null);
        jbtnVolver.setBorderPainted(false);
        jbtnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnVolver.setFocusPainted(false);
        jbtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelCategoriasLayout = new javax.swing.GroupLayout(jpanelCategorias);
        jpanelCategorias.setLayout(jpanelCategoriasLayout);
        jpanelCategoriasLayout.setHorizontalGroup(
            jpanelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelCategoriasLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(jpanelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnDonCalzzone, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnAdicionales, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPizzas, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(131, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelCategoriasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpanelCategoriasLayout.setVerticalGroup(
            jpanelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelCategoriasLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jbtnPizzas, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnAdicionales, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnDonCalzzone, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAdicionalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAdicionalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAdicionalesActionPerformed

    private void jbtnPizzasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPizzasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPizzasActionPerformed

    private void jbtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVolverActionPerformed
       this.dispose();
            jfprincipal app1 = new jfprincipal();
                app1.setVisible(true);
    }//GEN-LAST:event_jbtnVolverActionPerformed

    private void jbtnPizzasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPizzasMouseEntered
        jbtnPizzas.setBackground(new Color(0, 120, 174));
        jbtnPizzas.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_jbtnPizzasMouseEntered

    private void jbtnPizzasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPizzasMouseExited
        jbtnPizzas.setBackground(new Color(255,255,255));
        jbtnPizzas.setForeground(new java.awt.Color(0, 120, 174));
    }//GEN-LAST:event_jbtnPizzasMouseExited

    private void jbtnAdicionalesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnAdicionalesMouseEntered
        jbtnAdicionales.setBackground(new Color(0, 120, 174));
        jbtnAdicionales.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_jbtnAdicionalesMouseEntered

    private void jbtnDonCalzzoneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnDonCalzzoneMouseEntered
        jbtnDonCalzzone.setBackground(new Color(0, 120, 174));
        jbtnDonCalzzone.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_jbtnDonCalzzoneMouseEntered

    private void jbtnBebidasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnBebidasMouseEntered
        jbtnBebidas.setBackground(new Color(0, 120, 174));
        jbtnBebidas.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_jbtnBebidasMouseEntered

    private void jbtnAdicionalesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnAdicionalesMouseExited
        jbtnAdicionales.setBackground(new Color(255,255,255));
        jbtnAdicionales.setForeground(new java.awt.Color(0, 120, 174));
    }//GEN-LAST:event_jbtnAdicionalesMouseExited

    private void jbtnDonCalzzoneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnDonCalzzoneMouseExited
        jbtnDonCalzzone.setBackground(new Color(255,255,255));
        jbtnDonCalzzone.setForeground(new java.awt.Color(0, 120, 174));
    }//GEN-LAST:event_jbtnDonCalzzoneMouseExited

    private void jbtnBebidasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnBebidasMouseExited
        jbtnBebidas.setBackground(new Color(255,255,255));
        jbtnBebidas.setForeground(new java.awt.Color(0, 120, 174));
    }//GEN-LAST:event_jbtnBebidasMouseExited

    private void jbtnPizzasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPizzasMouseClicked
        
    }//GEN-LAST:event_jbtnPizzasMouseClicked

    public void setearIconos(){
        jbtnVolver.setIcon(setIconoBtn("/02_clasificacion_menu/05.png",jbtnVolver));
        this.setIconImage(new ImageIcon(getClass().getResource("/00_jf_principal/idm.png")).getImage());
    }
    
      public Icon setIconoBtn(String url, JButton btn){
    
        //jbtnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizza.png")));
        ImageIcon imgIcon = new ImageIcon(getClass().getResource(url));
            int widthBtn = btn.getWidth();
                int heightBtn = btn.getHeight();
        
                    ImageIcon iconoBtn = new ImageIcon(imgIcon.getImage().getScaledInstance(widthBtn, heightBtn, Image.SCALE_DEFAULT));
                        return iconoBtn;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfClasificacionMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfClasificacionMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfClasificacionMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfClasificacionMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfClasificacionMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnAdicionales;
    private javax.swing.JButton jbtnBebidas;
    private javax.swing.JButton jbtnDonCalzzone;
    private javax.swing.JButton jbtnPizzas;
    private javax.swing.JButton jbtnVolver;
    private javax.swing.JPanel jpanelCategorias;
    // End of variables declaration//GEN-END:variables
}
