/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.proyectofinal.frames;

import com.proyectofinal.clases.Consulta;
import com.proyectofinal.clases.Hash;
import com.proyectofinal.clases.empleado;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import jdk.nashorn.internal.ir.TryNode;

/**
 *
 * @author Manuel
 */
public final class jfIniciarSesion extends javax.swing.JFrame {

    String pass;
    
    /**
     * Creates new form jfIniciarSesion
     */
    public jfIniciarSesion() {
        initComponents();
            setearIconos();
                cerrar();
    }

        class jPanelGradient extends JPanel{  
            @Override
            protected void paintComponent(Graphics g){
                Graphics2D g2d = (Graphics2D) g;
                    int width = getWidth();
                    int height = getHeight();
                        Color colorUno = new Color(0, 120, 174);
                        Color colorDos = new Color(185, 238, 226);
                            GradientPaint gp = new GradientPaint(0,0,colorUno,180,height,colorDos);
                                g2d.setPaint(gp);
                                g2d.fillRect(0, 0, width, height);
            }
        }
         class jPanelGradientDos extends JPanel{  
            @Override
            protected void paintComponent(Graphics g){
                Graphics2D g2d = (Graphics2D) g;
                    int width = getWidth();
                    int height = getHeight();
                        Color colorUno = new Color(255,255,255);
                        Color colorDos = new Color(187,187,187);
                            GradientPaint gp = new GradientPaint(0,0,colorUno,180,height,colorDos);
                                g2d.setPaint(gp);
                                g2d.fillRect(0, 0, width, height);
            }
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new jPanelGradient();
        jbtnRegistrarEmpleado = new javax.swing.JButton();
        jbtnVolver = new javax.swing.JButton();
        jPanel2 = new jPanelGradientDos();
        jLabel3 = new javax.swing.JLabel();
        jtxtUsuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtPassword = new javax.swing.JPasswordField();
        jcbMostrar = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DOMINO´S PIZZA");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnRegistrarEmpleado.setBackground(new java.awt.Color(0, 120, 174));
        jbtnRegistrarEmpleado.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jbtnRegistrarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        jbtnRegistrarEmpleado.setText("ENTRAR");
        jbtnRegistrarEmpleado.setBorder(null);
        jbtnRegistrarEmpleado.setBorderPainted(false);
        jbtnRegistrarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnRegistrarEmpleado.setFocusPainted(false);
        jbtnRegistrarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnRegistrarEmpleadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnRegistrarEmpleadoMouseExited(evt);
            }
        });
        jbtnRegistrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegistrarEmpleadoActionPerformed(evt);
            }
        });

        jbtnVolver.setBackground(new java.awt.Color(161, 223, 219));
        jbtnVolver.setBorder(null);
        jbtnVolver.setBorderPainted(false);
        jbtnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnVolver.setFocusPainted(false);
        jbtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVolverActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("USUARIO");

        jtxtUsuario.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jtxtUsuario.setForeground(new java.awt.Color(51, 51, 51));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("CONTRASEÑA");

        jtxtPassword.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jtxtPassword.setForeground(new java.awt.Color(51, 51, 51));
        jtxtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPasswordActionPerformed(evt);
            }
        });

        jcbMostrar.setBackground(new java.awt.Color(187, 187, 187));
        jcbMostrar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jcbMostrar.setForeground(new java.awt.Color(51, 51, 51));
        jcbMostrar.setText("MOSTRAR");
        jcbMostrar.setBorder(null);
        jcbMostrar.setFocusPainted(false);
        jcbMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbMostrar)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtxtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(jtxtUsuario)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbMostrar)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(250, 250, 250)
                        .addComponent(jbtnRegistrarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnRegistrarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPasswordActionPerformed

    private void jbtnRegistrarEmpleadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnRegistrarEmpleadoMouseEntered
        jbtnRegistrarEmpleado.setBackground(new Color(0,120,174));
        jbtnRegistrarEmpleado.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_jbtnRegistrarEmpleadoMouseEntered

    private void jbtnRegistrarEmpleadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnRegistrarEmpleadoMouseExited
        jbtnRegistrarEmpleado.setBackground(new Color(255,255,255));
        jbtnRegistrarEmpleado.setForeground(new Color(0,120,174));
    }//GEN-LAST:event_jbtnRegistrarEmpleadoMouseExited

    private void jbtnRegistrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegistrarEmpleadoActionPerformed
       try {
            Consulta mysql = new Consulta();
            empleado emp = new empleado();
                emp.setUsuario(jtxtUsuario.getText());
                    pass = new String(jtxtPassword.getPassword());
                        Date date = new Date();
                            DateFormat fechaHora = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                                if(hayCamposVacios()==false){
                                    String thePassword = Hash.sha1(pass);
                                        emp.setUsuario(jtxtUsuario.getText());
                                        emp.setPassword(thePassword);
                                        emp.setUltimaSesion(fechaHora.format(date)); 
                                                if(mysql.iniciarSesion(emp)==true){
                                                    this.dispose();
                                                        jfprincipal _app_PRINCIPAL = new jfprincipal(emp);
                                                            _app_PRINCIPAL.setVisible(true);
                                                }else{
                                                      Icon error = new ImageIcon(getClass().getResource("/03_mensajes/errorEnRegistro.png"));
                                                      JOptionPane.showMessageDialog(null, "USUARIO NO REGISTRADO EN EL SISTEMA", "MENSAJE", JOptionPane.OK_OPTION, error);
                                                }
                                }
        } catch (HeadlessException e) {
            Icon error = new ImageIcon(getClass().getResource("/03_mensajes/errorEnRegistro.png"));
                JOptionPane.showMessageDialog(null, "ERROR EN EL INICIO DE SESIÓN", "MENSAJE", JOptionPane.OK_OPTION, error);
                    System.out.println(e);
                        System.out.println(Arrays.toString(e.getStackTrace()));
        } catch (IOException ex) {
            Logger.getLogger(jfIniciarSesion.class.getName()).log(Level.SEVERE, null, ex);
        }                 
    }//GEN-LAST:event_jbtnRegistrarEmpleadoActionPerformed

    public boolean hayCamposVacios(){
        if(jtxtUsuario.getText().equals("")||pass.equals("")){
            Icon camposVacios = new ImageIcon(getClass().getResource("/04_accounts/camposVacios.png"));
                JOptionPane.showMessageDialog(null, "DEBES LLENAR TODOS LOS CAMPOS", "MENSAJE", JOptionPane.OK_OPTION, camposVacios);
                    return true;
        }else{
            return false;
        }
    }
    
    private void jbtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVolverActionPerformed
        backFromThis();
    }//GEN-LAST:event_jbtnVolverActionPerformed

    private void jcbMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMostrarActionPerformed
        if(jcbMostrar.isSelected()){
            jtxtPassword.setEchoChar((char)0);
        }else{
            jtxtPassword.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_jcbMostrarActionPerformed

    public void cerrar(){
    
        try {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e){ //WindowEvent: import java.awt.event.WindowEvent;
                      confirmarCerrarVentana();
                }
            });
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
   
    public void backFromThis(){
        
        Icon question;
        question = new ImageIcon(getClass().getResource("/00_jf_principal/question.png"));
        
        int valor = JOptionPane.showConfirmDialog(null, "¿REALMENTE QUIERES REGRESAR Y CERRAR LA VENTANA?", "ATENCIÓN", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE,question);
        if(valor == JOptionPane.YES_OPTION){
            this.dispose(); 
                jfLoginOrCreateAcount app1 = new jfLoginOrCreateAcount();
                    app1.setVisible(true);
        } 
        
    }
   
    public void confirmarCerrarVentana(){
        backFromThis();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfIniciarSesion().setVisible(true);
            }
        });
    }
    
    public void setearIconos(){
        jbtnVolver.setIcon(setIconoBtn("/02_clasificacion_menu/05.png",jbtnVolver));
            this.setIconImage(new ImageIcon(getClass().getResource("/00_jf_principal/idm.png")).getImage());
    }
    
      public Icon setIconoBtn(String url, JButton btn){
        ImageIcon imgIcon = new ImageIcon(getClass().getResource(url));
            int widthBtn = btn.getWidth();
                int heightBtn = btn.getHeight();
                    ImageIcon iconoBtn = new ImageIcon(imgIcon.getImage().getScaledInstance(widthBtn, heightBtn, Image.SCALE_DEFAULT));
                        return iconoBtn;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtnRegistrarEmpleado;
    private javax.swing.JButton jbtnVolver;
    private javax.swing.JCheckBox jcbMostrar;
    private javax.swing.JPasswordField jtxtPassword;
    private javax.swing.JTextField jtxtUsuario;
    // End of variables declaration//GEN-END:variables
}
