/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.proyectofinal.frames;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Manuel
 */
public class jfLoginOrCreateAcount extends javax.swing.JFrame {

    /**
     * Creates new form jfLoginOrCreateAcount
     */
    public jfLoginOrCreateAcount() {
        initComponents();
            setearIconos();
                cerrar();
    }
    
     public void setearIconos(){
        jbtnVolver.setIcon(setIconoBtn("/02_clasificacion_menu/05.png",jbtnVolver));
        this.setIconImage(new ImageIcon(getClass().getResource("/00_jf_principal/idm.png")).getImage());
    }
    
      public Icon setIconoBtn(String url, JButton btn){
    
        //jbtnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizza.png")));
        ImageIcon imgIcon = new ImageIcon(getClass().getResource(url));
            int widthBtn = btn.getWidth();
                int heightBtn = btn.getHeight();
        
                    ImageIcon iconoBtn = new ImageIcon(imgIcon.getImage().getScaledInstance(widthBtn, heightBtn, Image.SCALE_DEFAULT));
                        return iconoBtn;
    }
    
    class jPanelGradient extends JPanel{
        
        @Override
        protected void paintComponent(Graphics g){
            Graphics2D g2d = (Graphics2D) g;
                int width = getWidth();
                int height = getHeight();
                    Color colorUno = new Color(0, 120, 174);
                    Color colorDos = new Color(185, 238, 226);
                        GradientPaint gp = new GradientPaint(0,0,colorUno,180,height,colorDos);
                            g2d.setPaint(gp);
                            g2d.fillRect(0, 0, width, height);
                
        }
    }

    public void cerrar(){
    
        try {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e){ //WindowEvent: import java.awt.event.WindowEvent;
                      confirmarCerrarVentana();
                }
            });
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    
    public void confirmarCerrarVentana(){
        Icon question;
        question = new ImageIcon(getClass().getResource("/00_jf_principal/question.png"));
        
        int valor = JOptionPane.showConfirmDialog(null, "¿REALMENTE QUIERES CERRAR LA VENTANA?", "ATENCIÓN", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE,question);
        if(valor == JOptionPane.YES_OPTION){
            this.dispose(); 
                jfprincipal app1 = new jfprincipal();
                    app1.setVisible(true);
        } 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpLogin = new jPanelGradient();
        jbtnCrearCuenta = new javax.swing.JButton();
        jbtnIniciarSesion = new javax.swing.JButton();
        jbtnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DOMINO´S PIZZA");
        setMaximumSize(new java.awt.Dimension(900, 500));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpLogin.setMaximumSize(new java.awt.Dimension(900, 500));
        jpLogin.setMinimumSize(new java.awt.Dimension(900, 500));
        jpLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnCrearCuenta.setBackground(new java.awt.Color(255, 255, 255));
        jbtnCrearCuenta.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jbtnCrearCuenta.setForeground(new java.awt.Color(0, 120, 174));
        jbtnCrearCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/04_accounts/crear_cuenta.png"))); // NOI18N
        jbtnCrearCuenta.setText("CREAR CUENTA");
        jbtnCrearCuenta.setBorder(null);
        jbtnCrearCuenta.setBorderPainted(false);
        jbtnCrearCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnCrearCuenta.setFocusPainted(false);
        jbtnCrearCuenta.setMaximumSize(new java.awt.Dimension(75, 32));
        jbtnCrearCuenta.setMinimumSize(new java.awt.Dimension(72, 32));
        jbtnCrearCuenta.setPreferredSize(new java.awt.Dimension(72, 32));
        jbtnCrearCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnCrearCuentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnCrearCuentaMouseExited(evt);
            }
        });
        jbtnCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCrearCuentaActionPerformed(evt);
            }
        });
        jpLogin.add(jbtnCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 470, 150));

        jbtnIniciarSesion.setBackground(new java.awt.Color(255, 255, 255));
        jbtnIniciarSesion.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jbtnIniciarSesion.setForeground(new java.awt.Color(0, 120, 174));
        jbtnIniciarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/04_accounts/iniciar_sesion.png"))); // NOI18N
        jbtnIniciarSesion.setText("INICIAR SESIÓN");
        jbtnIniciarSesion.setBorder(null);
        jbtnIniciarSesion.setBorderPainted(false);
        jbtnIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnIniciarSesion.setFocusPainted(false);
        jbtnIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnIniciarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnIniciarSesionMouseExited(evt);
            }
        });
        jbtnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIniciarSesionActionPerformed(evt);
            }
        });
        jpLogin.add(jbtnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 470, 150));

        jbtnVolver.setBackground(new java.awt.Color(161, 223, 219));
        jbtnVolver.setBorder(null);
        jbtnVolver.setBorderPainted(false);
        jbtnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVolverActionPerformed(evt);
            }
        });
        jpLogin.add(jbtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 80, 72));

        getContentPane().add(jpLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVolverActionPerformed
        this.dispose();
            jfprincipal app = new jfprincipal();
                app.setVisible(true);
    }//GEN-LAST:event_jbtnVolverActionPerformed

    private void jbtnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCrearCuentaActionPerformed
        
        this.dispose();
            crearCuentaEmpleado emp = new crearCuentaEmpleado();
                emp.setVisible(true);
         
    }//GEN-LAST:event_jbtnCrearCuentaActionPerformed

    private void jbtnIniciarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnIniciarSesionMouseEntered
            jbtnIniciarSesion.setBackground(new Color(0,120,174));
            jbtnIniciarSesion.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_jbtnIniciarSesionMouseEntered

    private void jbtnIniciarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnIniciarSesionMouseExited
            jbtnIniciarSesion.setBackground(new Color(255,255,255));
            jbtnIniciarSesion.setForeground(new Color(0,120,174));
    }//GEN-LAST:event_jbtnIniciarSesionMouseExited

    private void jbtnCrearCuentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnCrearCuentaMouseEntered
            jbtnCrearCuenta.setBackground(new Color(0,120,174));
            jbtnCrearCuenta.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_jbtnCrearCuentaMouseEntered

    private void jbtnCrearCuentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnCrearCuentaMouseExited
            jbtnCrearCuenta.setBackground(new Color(255,255,255));
            jbtnCrearCuenta.setForeground(new Color(0,120,174));
    }//GEN-LAST:event_jbtnCrearCuentaMouseExited

    private void jbtnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIniciarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnIniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfLoginOrCreateAcount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfLoginOrCreateAcount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfLoginOrCreateAcount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfLoginOrCreateAcount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfLoginOrCreateAcount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnCrearCuenta;
    private javax.swing.JButton jbtnIniciarSesion;
    private javax.swing.JButton jbtnVolver;
    private javax.swing.JPanel jpLogin;
    // End of variables declaration//GEN-END:variables
}
