/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.proyectofinal.frames;

import com.proyectofinal.clases.conection;
import com.proyectofinal.clases.empleado;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.Image;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Manuel
 */
public class jfMesas extends javax.swing.JFrame {
    
    empleado emp = null;
    
    /**
     * Creates new form jfMesas
     */
    public jfMesas() {
        initComponents();
    }

    public jfMesas(empleado emp) {
        this.emp = emp;
            initComponents();
                setImagesToComponents();
    }
    
      class jPanelGradient extends JPanel{
            @Override
            protected void paintComponent(Graphics g){
                Graphics2D g2d = (Graphics2D) g;
                    int width = getWidth();
                    int height = getHeight();
                        Color colorUno = new Color(0, 120, 174);
                        Color colorDos = new Color(185, 238, 226);
                            GradientPaint gp = new GradientPaint(0,0,colorUno,180,height,colorDos);
                                g2d.setPaint(gp);
                                g2d.fillRect(0, 0, width, height);

            }
        }   
    
      class jPanelGradient2 extends JPanel{  
            @Override
            protected void paintComponent(Graphics g){
                Graphics2D g2d = (Graphics2D) g;
                    int width = getWidth();
                    int height = getHeight();                
                        Color colorUno = new Color(255,255,255);
                        Color colorDos = new Color(187,187,187);
                            GradientPaint gp = new GradientPaint(0,0,colorUno,180,height,colorDos);
                                g2d.setPaint(gp);
                                g2d.fillRect(0, 0, width, height);
            }
        }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelCategorias = new jPanelGradient();
        jbtnVolver = new javax.swing.JButton();
        jbtnDatosARegistrar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jpanelDatosATraer1 = new jPanelGradient2();
        jSpinner1 = new javax.swing.JSpinner();
        jbtnRegistrarMesa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DOMINO´S PIZZA");

        jpanelCategorias.setMaximumSize(new java.awt.Dimension(900, 500));
        jpanelCategorias.setMinimumSize(new java.awt.Dimension(900, 500));

        jbtnVolver.setBackground(new java.awt.Color(148, 214, 216));
        jbtnVolver.setBorder(null);
        jbtnVolver.setBorderPainted(false);
        jbtnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnVolver.setFocusPainted(false);
        jbtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVolverActionPerformed(evt);
            }
        });

        jbtnDatosARegistrar.setBackground(new java.awt.Color(0, 100, 145));

        jLabel5.setBackground(new java.awt.Color(0, 100, 145));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MESA");

        javax.swing.GroupLayout jbtnDatosARegistrarLayout = new javax.swing.GroupLayout(jbtnDatosARegistrar);
        jbtnDatosARegistrar.setLayout(jbtnDatosARegistrarLayout);
        jbtnDatosARegistrarLayout.setHorizontalGroup(
            jbtnDatosARegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbtnDatosARegistrarLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel5)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jbtnDatosARegistrarLayout.setVerticalGroup(
            jbtnDatosARegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbtnDatosARegistrarLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSpinner1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N

        javax.swing.GroupLayout jpanelDatosATraer1Layout = new javax.swing.GroupLayout(jpanelDatosATraer1);
        jpanelDatosATraer1.setLayout(jpanelDatosATraer1Layout);
        jpanelDatosATraer1Layout.setHorizontalGroup(
            jpanelDatosATraer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelDatosATraer1Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jpanelDatosATraer1Layout.setVerticalGroup(
            jpanelDatosATraer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelDatosATraer1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jbtnRegistrarMesa.setBackground(new java.awt.Color(0, 120, 174));
        jbtnRegistrarMesa.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jbtnRegistrarMesa.setForeground(new java.awt.Color(255, 255, 255));
        jbtnRegistrarMesa.setText("REGISTRAR");
        jbtnRegistrarMesa.setBorder(null);
        jbtnRegistrarMesa.setBorderPainted(false);
        jbtnRegistrarMesa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnRegistrarMesa.setFocusPainted(false);
        jbtnRegistrarMesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnRegistrarMesaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnRegistrarMesaMouseExited(evt);
            }
        });
        jbtnRegistrarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegistrarMesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelCategoriasLayout = new javax.swing.GroupLayout(jpanelCategorias);
        jpanelCategorias.setLayout(jpanelCategoriasLayout);
        jpanelCategoriasLayout.setHorizontalGroup(
            jpanelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelCategoriasLayout.createSequentialGroup()
                .addGroup(jpanelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelCategoriasLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jbtnDatosARegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jpanelDatosATraer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jbtnRegistrarMesa))
                    .addGroup(jpanelCategoriasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanelCategoriasLayout.setVerticalGroup(
            jpanelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelCategoriasLayout.createSequentialGroup()
                .addGroup(jpanelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelCategoriasLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jpanelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpanelDatosATraer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnDatosARegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jpanelCategoriasLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jbtnRegistrarMesa)))
                .addGap(32, 32, 32)
                .addComponent(jbtnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVolverActionPerformed
         jfRegistrarActualizarEliminar app1 = new jfRegistrarActualizarEliminar(emp);    
                this.dispose();
                    app1.setVisible(true);
    }//GEN-LAST:event_jbtnVolverActionPerformed

    private void jbtnRegistrarMesaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnRegistrarMesaMouseEntered
        jbtnRegistrarMesa.setBackground(new Color(0,120,174));
        jbtnRegistrarMesa.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_jbtnRegistrarMesaMouseEntered

    private void jbtnRegistrarMesaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnRegistrarMesaMouseExited
        jbtnRegistrarMesa.setBackground(new Color(255,255,255));
        jbtnRegistrarMesa.setForeground(new Color(0,120,174));
    }//GEN-LAST:event_jbtnRegistrarMesaMouseExited

    private void jbtnRegistrarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegistrarMesaActionPerformed
        
        try {
                
                int valor =  0;
                    valor =  (Integer) jSpinner1.getValue();
                
                if(valor!=0){
                  
                        String valorString = String.valueOf(valor);
                            String mesaIdentificador = "MESA-"+valorString; 
                    
                    if(mesaExisteEnDB(mesaIdentificador)==0){
                        conection conectar = new conection();
                        Connection cn = conectar.getConection();
                        String query = "{CALL REGISTRAR_MESA(?,?)}";
                        CallableStatement cts = cn.prepareCall(query);
                            cts.setString(1, mesaIdentificador);
                            cts.setInt(2, 1); //1=true, la disponibilidad inicial de la mesa. :):

                            int res = cts.executeUpdate();

                                if(res>0){
                                    Icon registroExitoso = new ImageIcon(getClass().getResource("/03_mensajes/succesful.png"));
                                        JOptionPane.showMessageDialog(null, "MESA REGISTRADA CON ÉXITO", "MENSAJE", JOptionPane.OK_OPTION, registroExitoso);
                                            cleanInput();
                                }else{
                                    System.out.println("resulset");
                                    cleanInput();
                                        throw new SQLException();
                                }
                    }else{
                        System.out.println("ya existe");
                         cleanInput();
                              throw new SQLException();
                    }
                    
                    
                }else{
                    Icon algunErrorsito= new ImageIcon(getClass().getResource("/03_mensajes/errorEnRegistro.png"));
                            JOptionPane.showMessageDialog(null, "EL VALOR NO PUEDE SER CERO", "ATENCIÓN",JOptionPane.OK_OPTION, algunErrorsito);
                }
                
            
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            Icon algunErrorsito= new ImageIcon(getClass().getResource("/03_mensajes/errorEnRegistro.png"));
               JOptionPane.showMessageDialog(null, "VERIFICA LOS DATOS INGRESADOS, PUEDE QUE LA MESA YA HAYA SIDO REGISTRADA", "ATENCIÓN",JOptionPane.OK_OPTION, algunErrorsito);
               
        }
        
    }//GEN-LAST:event_jbtnRegistrarMesaActionPerformed

    public int mesaExisteEnDB(String valor){
        try {
            conection conectar = new conection();
            CallableStatement cts = null;
            Connection con = conectar.getConection();
                ResultSet rs;
                String query = "{CALL VALIDAR_MESA(?)}";
                    cts = con.prepareCall(query);
                        cts.setString(1, valor);
                            rs = cts.executeQuery();
                                if(rs.next()){
                                    //si hay un registro significa que no podemos usarlo, por lo tanto
                                    return rs.getInt(1);
                                }
                                    return 1;
                        
        } catch (ClassNotFoundException | SQLException e) {
            return 1;
        }
    }
    
        public void setImagesToComponents(){
            this.setIconImage(new ImageIcon(getClass().getResource("/00_jf_principal/idm.png")).getImage());
                jbtnVolver.setIcon(setIconoBtn("/02_clasificacion_menu/05.png", jbtnVolver));
    }
    
    public Icon setIconoBtn(String url, JButton btn){
        ImageIcon imgIcon = new ImageIcon(getClass().getResource(url));
            int widthBtn = btn.getWidth();
                int heightBtn = btn.getHeight();        
                    ImageIcon iconoBtn = new ImageIcon(imgIcon.getImage().getScaledInstance(widthBtn, heightBtn, Image.SCALE_DEFAULT));
                        return iconoBtn;
    }
    
    public void cleanInput(){
        jSpinner1.setValue(0); 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfMesas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JPanel jbtnDatosARegistrar;
    private javax.swing.JButton jbtnRegistrarMesa;
    private javax.swing.JButton jbtnVolver;
    private javax.swing.JPanel jpanelCategorias;
    private javax.swing.JPanel jpanelDatosATraer1;
    // End of variables declaration//GEN-END:variables
}
