/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.proyectofinal.frames;

import com.proyectofinal.clases.Producto;
import com.proyectofinal.clases.empleado;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Iosef14
 */
public final class jfMenuPizzas extends javax.swing.JFrame {
    public static ArrayList<Producto> Lista_producto = new ArrayList<Producto> ();
        Producto pizaQueso = new Producto();
        Producto pizaCincoCarnes = new Producto();
        Producto pizaHawaiana = new Producto();     
        Producto pizaDeluxe = new Producto();   
            empleado emp = null;
    
    /**
     * Creates new form jfMenuPizzas
     */
    public jfMenuPizzas() {
        initComponents();
    }

    public jfMenuPizzas(empleado emp) {
        this.emp = emp;
            initComponents();
                setearIconosComponentes();
                    crearObjetosYSetearDatos();
                        cerrar();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jpMenuPizzas = new javax.swing.JPanel();
        jp01 = new javax.swing.JPanel();
        jlblNombrePizza = new javax.swing.JLabel();
        jlblFotoPizzaQueso = new javax.swing.JLabel();
        jcbTamanioPQ = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jsCantidadPQ = new javax.swing.JSpinner();
        jbtnAgregarPizzaUno = new javax.swing.JButton();
        jlblPrecioPizza = new javax.swing.JLabel();
        jp2 = new javax.swing.JPanel();
        jlblNombrePizza1 = new javax.swing.JLabel();
        jlblFotoPizzaCincoCarnes = new javax.swing.JLabel();
        jcbTamanioPCC = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jsCantidadPCC = new javax.swing.JSpinner();
        jbtnAgregarPizzaDos = new javax.swing.JButton();
        jlblPrecioPizza1 = new javax.swing.JLabel();
        jp3 = new javax.swing.JPanel();
        jlblNombrePizza2 = new javax.swing.JLabel();
        jlblFotoPizzaHawaiana = new javax.swing.JLabel();
        jcbTamanioPH = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jsCantidadPH = new javax.swing.JSpinner();
        jbtnAgregarPizzaTres = new javax.swing.JButton();
        jlblPrecioPizza2 = new javax.swing.JLabel();
        jp4 = new javax.swing.JPanel();
        jlblNombrePizza3 = new javax.swing.JLabel();
        jlblFotoPizzaDeluxe = new javax.swing.JLabel();
        jcbTamanioPD = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jsCantidadPD = new javax.swing.JSpinner();
        jbtnAgregarPizzaCuatro = new javax.swing.JButton();
        jlblPrecioPizza3 = new javax.swing.JLabel();
        jbtnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DOMINO´S PIZZA");
        setMaximumSize(new java.awt.Dimension(900, 500));
        setMinimumSize(new java.awt.Dimension(923, 500));
        setResizable(false);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(101, 1000));

        jpMenuPizzas.setBackground(new java.awt.Color(255, 255, 255));
        jpMenuPizzas.setPreferredSize(new java.awt.Dimension(899, 934));

        jp01.setBackground(new java.awt.Color(204, 204, 204));

        jlblNombrePizza.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblNombrePizza.setForeground(new java.awt.Color(102, 102, 255));
        jlblNombrePizza.setText("PIZZA DE QUESO");

        jlblFotoPizzaQueso.setBackground(new java.awt.Color(153, 153, 153));

        jcbTamanioPQ.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jcbTamanioPQ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "PERSONAL", "MEDIANA", "GRANDE" }));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("CANTIDAD");

        jsCantidadPQ.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jbtnAgregarPizzaUno.setBackground(new java.awt.Color(0, 120, 174));
        jbtnAgregarPizzaUno.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbtnAgregarPizzaUno.setForeground(new java.awt.Color(255, 255, 255));
        jbtnAgregarPizzaUno.setText("AGREGAR");
        jbtnAgregarPizzaUno.setBorder(null);
        jbtnAgregarPizzaUno.setBorderPainted(false);
        jbtnAgregarPizzaUno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnAgregarPizzaUno.setFocusPainted(false);
        jbtnAgregarPizzaUno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnAgregarPizzaUnoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnAgregarPizzaUnoMouseExited(evt);
            }
        });
        jbtnAgregarPizzaUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgregarPizzaUnoActionPerformed(evt);
            }
        });

        jlblPrecioPizza.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblPrecioPizza.setForeground(new java.awt.Color(102, 102, 255));
        jlblPrecioPizza.setText("Q 75.89");

        javax.swing.GroupLayout jp01Layout = new javax.swing.GroupLayout(jp01);
        jp01.setLayout(jp01Layout);
        jp01Layout.setHorizontalGroup(
            jp01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp01Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblFotoPizzaQueso, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
            .addGroup(jp01Layout.createSequentialGroup()
                .addGroup(jp01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp01Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jbtnAgregarPizzaUno, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp01Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jp01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jp01Layout.createSequentialGroup()
                                .addComponent(jlblNombrePizza)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlblPrecioPizza))
                            .addGroup(jp01Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jsCantidadPQ, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbTamanioPQ, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jp01Layout.setVerticalGroup(
            jp01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp01Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jp01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNombrePizza)
                    .addComponent(jlblPrecioPizza))
                .addGap(12, 12, 12)
                .addComponent(jlblFotoPizzaQueso, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jp01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jsCantidadPQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbTamanioPQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jbtnAgregarPizzaUno)
                .addGap(19, 19, 19))
        );

        jp2.setBackground(new java.awt.Color(204, 204, 204));

        jlblNombrePizza1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblNombrePizza1.setForeground(new java.awt.Color(102, 102, 255));
        jlblNombrePizza1.setText("CINCO CARNES");

        jlblFotoPizzaCincoCarnes.setBackground(new java.awt.Color(153, 153, 153));

        jcbTamanioPCC.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jcbTamanioPCC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "PERSONAL", "MEDIANA", "GRANDE" }));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("CANTIDAD");

        jsCantidadPCC.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jbtnAgregarPizzaDos.setBackground(new java.awt.Color(0, 120, 174));
        jbtnAgregarPizzaDos.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbtnAgregarPizzaDos.setForeground(new java.awt.Color(255, 255, 255));
        jbtnAgregarPizzaDos.setText("AGREGAR");
        jbtnAgregarPizzaDos.setBorder(null);
        jbtnAgregarPizzaDos.setBorderPainted(false);
        jbtnAgregarPizzaDos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnAgregarPizzaDos.setFocusPainted(false);
        jbtnAgregarPizzaDos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnAgregarPizzaDosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnAgregarPizzaDosMouseExited(evt);
            }
        });
        jbtnAgregarPizzaDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgregarPizzaDosActionPerformed(evt);
            }
        });

        jlblPrecioPizza1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblPrecioPizza1.setForeground(new java.awt.Color(102, 102, 255));
        jlblPrecioPizza1.setText("Q 85.89");

        javax.swing.GroupLayout jp2Layout = new javax.swing.GroupLayout(jp2);
        jp2.setLayout(jp2Layout);
        jp2Layout.setHorizontalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblFotoPizzaCincoCarnes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
            .addGroup(jp2Layout.createSequentialGroup()
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jbtnAgregarPizzaDos, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jp2Layout.createSequentialGroup()
                                .addComponent(jlblNombrePizza1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlblPrecioPizza1))
                            .addGroup(jp2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jsCantidadPCC, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbTamanioPCC, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jp2Layout.setVerticalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNombrePizza1)
                    .addComponent(jlblPrecioPizza1))
                .addGap(12, 12, 12)
                .addComponent(jlblFotoPizzaCincoCarnes, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jsCantidadPCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbTamanioPCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jbtnAgregarPizzaDos)
                .addGap(19, 19, 19))
        );

        jp3.setBackground(new java.awt.Color(204, 204, 204));

        jlblNombrePizza2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblNombrePizza2.setForeground(new java.awt.Color(102, 102, 255));
        jlblNombrePizza2.setText("HAWAIANA");

        jlblFotoPizzaHawaiana.setBackground(new java.awt.Color(153, 153, 153));

        jcbTamanioPH.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jcbTamanioPH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "PERSONAL", "MEDIANA", "GRANDE" }));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("CANTIDAD");

        jsCantidadPH.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jbtnAgregarPizzaTres.setBackground(new java.awt.Color(0, 120, 174));
        jbtnAgregarPizzaTres.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbtnAgregarPizzaTres.setForeground(new java.awt.Color(255, 255, 255));
        jbtnAgregarPizzaTres.setText("AGREGAR");
        jbtnAgregarPizzaTres.setBorder(null);
        jbtnAgregarPizzaTres.setBorderPainted(false);
        jbtnAgregarPizzaTres.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnAgregarPizzaTres.setFocusPainted(false);
        jbtnAgregarPizzaTres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnAgregarPizzaTresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnAgregarPizzaTresMouseExited(evt);
            }
        });
        jbtnAgregarPizzaTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgregarPizzaTresActionPerformed(evt);
            }
        });

        jlblPrecioPizza2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblPrecioPizza2.setForeground(new java.awt.Color(102, 102, 255));
        jlblPrecioPizza2.setText("Q 95.89");

        javax.swing.GroupLayout jp3Layout = new javax.swing.GroupLayout(jp3);
        jp3.setLayout(jp3Layout);
        jp3Layout.setHorizontalGroup(
            jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblFotoPizzaHawaiana, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
            .addGroup(jp3Layout.createSequentialGroup()
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp3Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jbtnAgregarPizzaTres, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jp3Layout.createSequentialGroup()
                                .addComponent(jlblNombrePizza2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlblPrecioPizza2))
                            .addGroup(jp3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jsCantidadPH, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbTamanioPH, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jp3Layout.setVerticalGroup(
            jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNombrePizza2)
                    .addComponent(jlblPrecioPizza2))
                .addGap(12, 12, 12)
                .addComponent(jlblFotoPizzaHawaiana, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jsCantidadPH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbTamanioPH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jbtnAgregarPizzaTres)
                .addGap(19, 19, 19))
        );

        jp4.setBackground(new java.awt.Color(204, 204, 204));

        jlblNombrePizza3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblNombrePizza3.setForeground(new java.awt.Color(102, 102, 255));
        jlblNombrePizza3.setText("DELUXE");

        jlblFotoPizzaDeluxe.setBackground(new java.awt.Color(153, 153, 153));

        jcbTamanioPD.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jcbTamanioPD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "PERSONAL", "MEDIANA", "GRANDE" }));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("CANTIDAD");

        jsCantidadPD.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jbtnAgregarPizzaCuatro.setBackground(new java.awt.Color(0, 120, 174));
        jbtnAgregarPizzaCuatro.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbtnAgregarPizzaCuatro.setForeground(new java.awt.Color(255, 255, 255));
        jbtnAgregarPizzaCuatro.setText("AGREGAR");
        jbtnAgregarPizzaCuatro.setBorder(null);
        jbtnAgregarPizzaCuatro.setBorderPainted(false);
        jbtnAgregarPizzaCuatro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnAgregarPizzaCuatro.setFocusPainted(false);
        jbtnAgregarPizzaCuatro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnAgregarPizzaCuatroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnAgregarPizzaCuatroMouseExited(evt);
            }
        });
        jbtnAgregarPizzaCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgregarPizzaCuatroActionPerformed(evt);
            }
        });

        jlblPrecioPizza3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblPrecioPizza3.setForeground(new java.awt.Color(102, 102, 255));
        jlblPrecioPizza3.setText("Q 105.89");

        javax.swing.GroupLayout jp4Layout = new javax.swing.GroupLayout(jp4);
        jp4.setLayout(jp4Layout);
        jp4Layout.setHorizontalGroup(
            jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblFotoPizzaDeluxe, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
            .addGroup(jp4Layout.createSequentialGroup()
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp4Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jbtnAgregarPizzaCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jp4Layout.createSequentialGroup()
                                .addComponent(jlblNombrePizza3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlblPrecioPizza3))
                            .addGroup(jp4Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jsCantidadPD, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbTamanioPD, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jp4Layout.setVerticalGroup(
            jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNombrePizza3)
                    .addComponent(jlblPrecioPizza3))
                .addGap(12, 12, 12)
                .addComponent(jlblFotoPizzaDeluxe, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jsCantidadPD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbTamanioPD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jbtnAgregarPizzaCuatro)
                .addGap(19, 19, 19))
        );

        jbtnVolver.setBackground(new java.awt.Color(255, 255, 255));
        jbtnVolver.setBorder(null);
        jbtnVolver.setBorderPainted(false);
        jbtnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnVolver.setFocusPainted(false);
        jbtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpMenuPizzasLayout = new javax.swing.GroupLayout(jpMenuPizzas);
        jpMenuPizzas.setLayout(jpMenuPizzasLayout);
        jpMenuPizzasLayout.setHorizontalGroup(
            jpMenuPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuPizzasLayout.createSequentialGroup()
                .addGroup(jpMenuPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpMenuPizzasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpMenuPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuPizzasLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpMenuPizzasLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jp01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(jp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49))
        );
        jpMenuPizzasLayout.setVerticalGroup(
            jpMenuPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuPizzasLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jpMenuPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jp01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jpMenuPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jbtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jpMenuPizzas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 923, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAgregarPizzaUnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnAgregarPizzaUnoMouseEntered
        jbtnAgregarPizzaUno.setBackground(new Color(0,120,174));
        jbtnAgregarPizzaUno.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_jbtnAgregarPizzaUnoMouseEntered

    private void jbtnAgregarPizzaUnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnAgregarPizzaUnoMouseExited
        jbtnAgregarPizzaUno.setBackground(new Color(255,255,255));
        jbtnAgregarPizzaUno.setForeground(new Color(0,120,174));
    }//GEN-LAST:event_jbtnAgregarPizzaUnoMouseExited

    private void jbtnAgregarPizzaUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgregarPizzaUnoActionPerformed
        
        
    }//GEN-LAST:event_jbtnAgregarPizzaUnoActionPerformed

    private void jbtnAgregarPizzaDosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnAgregarPizzaDosMouseEntered
          jbtnAgregarPizzaDos.setBackground(new Color(0,120,174));
          jbtnAgregarPizzaDos.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_jbtnAgregarPizzaDosMouseEntered

    private void jbtnAgregarPizzaDosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnAgregarPizzaDosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAgregarPizzaDosMouseExited

    private void jbtnAgregarPizzaDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgregarPizzaDosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAgregarPizzaDosActionPerformed

    private void jbtnAgregarPizzaTresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnAgregarPizzaTresMouseEntered
          jbtnAgregarPizzaTres.setBackground(new Color(0,120,174));
            jbtnAgregarPizzaTres.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_jbtnAgregarPizzaTresMouseEntered

    private void jbtnAgregarPizzaTresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnAgregarPizzaTresMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAgregarPizzaTresMouseExited

    private void jbtnAgregarPizzaTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgregarPizzaTresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAgregarPizzaTresActionPerformed

    private void jbtnAgregarPizzaCuatroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnAgregarPizzaCuatroMouseEntered
          jbtnAgregarPizzaCuatro.setBackground(new Color(0,120,174));
            jbtnAgregarPizzaCuatro.setForeground(new Color(255,255,255));// TODO add your handling code here:
    }//GEN-LAST:event_jbtnAgregarPizzaCuatroMouseEntered

    private void jbtnAgregarPizzaCuatroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnAgregarPizzaCuatroMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAgregarPizzaCuatroMouseExited

    private void jbtnAgregarPizzaCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgregarPizzaCuatroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAgregarPizzaCuatroActionPerformed

    private void jbtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVolverActionPerformed
        backFromThis();
    }//GEN-LAST:event_jbtnVolverActionPerformed

    public void backFromThis(){
        jfClasificacionMenu menuClas = new jfClasificacionMenu(emp);
            this.dispose();
                menuClas.setVisible(true);
    }
    
    public void crearObjetosYSetearDatos(){
        //PIZA 01
        pizaQueso.setId(1); 
        pizaQueso.setNombre("PIZA DE QUESO");
        pizaQueso.setCategoria("PIZZA");
        pizaQueso.setPrecio(75.89); 
        
            //PIZA 02
            pizaCincoCarnes.setId(2); 
            pizaCincoCarnes.setNombre("PIZA CINCO CARNES");
            pizaCincoCarnes.setCategoria("PIZZA");
            pizaCincoCarnes.setPrecio(85.89); 
            
                //PIZA 03
                pizaHawaiana.setId(3); 
                pizaHawaiana.setNombre("PIZA HAWAIANA");
                pizaHawaiana.setCategoria("PIZZA");
                pizaHawaiana.setPrecio(95.89);
                
                    //PIZA 04
                    pizaDeluxe.setId(4); 
                    pizaDeluxe.setNombre("PIZA DELUXE");
                    pizaDeluxe.setCategoria("FAVORITOS");
                    pizaDeluxe.setPrecio(105.89);

    }
    
    public void setearIconosComponentes(){
        jlblFotoPizzaQueso.setIcon(new ImageIcon(getClass().getResource("/05_menu/pizzas/01.jpg"))); 
        jlblFotoPizzaCincoCarnes.setIcon(new ImageIcon(getClass().getResource("/05_menu/pizzas/02.jpg")));
        jlblFotoPizzaHawaiana.setIcon(new ImageIcon(getClass().getResource("/05_menu/pizzas/03.jpg")));
        jlblFotoPizzaDeluxe.setIcon(new ImageIcon(getClass().getResource("/05_menu/pizzas/04.jpg")));
        this.setIconImage(new ImageIcon(getClass().getResource("/00_jf_principal/idm.png")).getImage());
        jbtnVolver.setIcon(setIconoBtn("/06_mesasClientes/05.png",jbtnVolver));
    }
    
    public void cerrar(){
    
        try {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e){ //WindowEvent: import java.awt.event.WindowEvent;
                      confirmarCerrarVentana();
                }
            });
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    
    public void confirmarCerrarVentana(){
        Icon question;
        question = new ImageIcon(getClass().getResource("/00_jf_principal/question.png"));
        
        int valor = JOptionPane.showConfirmDialog(null, "¿REALMENTE QUIERES CERRAR LA VENTANA?", "ATENCIÓN", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE,question);
        if(valor == JOptionPane.YES_OPTION){
                jfClasificacionMenu cmenu = new jfClasificacionMenu(emp);
                    this.dispose(); 
                        cmenu.setVisible(true);
        }
    }
    
       public Icon setIconoBtn(String url, JButton btn){
    
        //jbtnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizza.png")));
        ImageIcon imgIcon = new ImageIcon(getClass().getResource(url));
            int widthBtn = btn.getWidth();
                int heightBtn = btn.getHeight();
        
                    ImageIcon iconoBtn = new ImageIcon(imgIcon.getImage().getScaledInstance(widthBtn, heightBtn, Image.SCALE_DEFAULT));
                        return iconoBtn;
    }
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfMenuPizzas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfMenuPizzas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfMenuPizzas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfMenuPizzas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfMenuPizzas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnAgregarPizzaCuatro;
    private javax.swing.JButton jbtnAgregarPizzaDos;
    private javax.swing.JButton jbtnAgregarPizzaTres;
    private javax.swing.JButton jbtnAgregarPizzaUno;
    private javax.swing.JButton jbtnVolver;
    private javax.swing.JComboBox<String> jcbTamanioPCC;
    private javax.swing.JComboBox<String> jcbTamanioPD;
    private javax.swing.JComboBox<String> jcbTamanioPH;
    private javax.swing.JComboBox<String> jcbTamanioPQ;
    private javax.swing.JLabel jlblFotoPizzaCincoCarnes;
    private javax.swing.JLabel jlblFotoPizzaDeluxe;
    private javax.swing.JLabel jlblFotoPizzaHawaiana;
    private javax.swing.JLabel jlblFotoPizzaQueso;
    private javax.swing.JLabel jlblNombrePizza;
    private javax.swing.JLabel jlblNombrePizza1;
    private javax.swing.JLabel jlblNombrePizza2;
    private javax.swing.JLabel jlblNombrePizza3;
    private javax.swing.JLabel jlblPrecioPizza;
    private javax.swing.JLabel jlblPrecioPizza1;
    private javax.swing.JLabel jlblPrecioPizza2;
    private javax.swing.JLabel jlblPrecioPizza3;
    private javax.swing.JPanel jp01;
    private javax.swing.JPanel jp2;
    private javax.swing.JPanel jp3;
    private javax.swing.JPanel jp4;
    private javax.swing.JPanel jpMenuPizzas;
    private javax.swing.JSpinner jsCantidadPCC;
    private javax.swing.JSpinner jsCantidadPD;
    private javax.swing.JSpinner jsCantidadPH;
    private javax.swing.JSpinner jsCantidadPQ;
    // End of variables declaration//GEN-END:variables
}
