/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.proyectofinal.frames;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Manuel
 */
public class jfprincipal extends javax.swing.JFrame {
    
    /**
     * Creates new form jfprincipal
     */
    public jfprincipal() {
        initComponents();
            setImagesToComponents();
                cerrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpDown = new javax.swing.JPanel();
        jbtnProductoUno = new javax.swing.JButton();
        jbtnProductoTres = new javax.swing.JButton();
        jbtnProductoDos = new javax.swing.JButton();
        jpUpMenuOptions = new javax.swing.JPanel();
        jbtnDashboard1 = new javax.swing.JButton();
        jbtnMenu1 = new javax.swing.JButton();
        jbtnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DOMINO´S PIZZA");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(900, 500));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setResizable(false);

        jpDown.setBackground(new java.awt.Color(255, 255, 255));
        jpDown.setMaximumSize(new java.awt.Dimension(900, 500));
        jpDown.setMinimumSize(new java.awt.Dimension(900, 500));
        jpDown.setPreferredSize(new java.awt.Dimension(900, 500));
        jpDown.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnProductoUno.setBackground(new java.awt.Color(255, 255, 255));
        jbtnProductoUno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnProductoUno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnProductoUno.setFocusPainted(false);
        jbtnProductoUno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnProductoUnoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnProductoUnoMouseExited(evt);
            }
        });
        jpDown.add(jbtnProductoUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 540, 370));

        jbtnProductoTres.setBackground(new java.awt.Color(255, 255, 255));
        jbtnProductoTres.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnProductoTres.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnProductoTres.setFocusPainted(false);
        jbtnProductoTres.setPreferredSize(new java.awt.Dimension(30, 15));
        jbtnProductoTres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnProductoTresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnProductoTresMouseExited(evt);
            }
        });
        jpDown.add(jbtnProductoTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 250, 180));

        jbtnProductoDos.setBackground(new java.awt.Color(255, 255, 255));
        jbtnProductoDos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnProductoDos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnProductoDos.setFocusPainted(false);
        jbtnProductoDos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnProductoDosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnProductoDosMouseExited(evt);
            }
        });
        jpDown.add(jbtnProductoDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 250, 180));

        jpUpMenuOptions.setBackground(new java.awt.Color(0, 100, 145));
        jpUpMenuOptions.setPreferredSize(new java.awt.Dimension(900, 70));

        jbtnDashboard1.setBackground(new java.awt.Color(0, 100, 145));
        jbtnDashboard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/00_jf_principal/miniLogoDominos.png"))); // NOI18N
        jbtnDashboard1.setBorder(null);
        jbtnDashboard1.setBorderPainted(false);
        jbtnDashboard1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnDashboard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDashboardActionPerformed(evt);
            }
        });

        jbtnMenu1.setBackground(new java.awt.Color(0, 100, 145));
        jbtnMenu1.setBorder(null);
        jbtnMenu1.setBorderPainted(false);
        jbtnMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMenuActionPerformed(evt);
            }
        });

        jbtnLogin.setBackground(new java.awt.Color(0, 100, 145));
        jbtnLogin.setBorder(null);
        jbtnLogin.setBorderPainted(false);
        jbtnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpUpMenuOptionsLayout = new javax.swing.GroupLayout(jpUpMenuOptions);
        jpUpMenuOptions.setLayout(jpUpMenuOptionsLayout);
        jpUpMenuOptionsLayout.setHorizontalGroup(
            jpUpMenuOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUpMenuOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnDashboard1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 679, Short.MAX_VALUE)
                .addComponent(jbtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpUpMenuOptionsLayout.setVerticalGroup(
            jpUpMenuOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUpMenuOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpUpMenuOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnDashboard1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, Short.MAX_VALUE)
                    .addGroup(jpUpMenuOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jbtnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                        .addComponent(jbtnMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jpDown.add(jpUpMenuOptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMenuActionPerformed

        this.dispose();
        jfClasificacionMenu cm = new jfClasificacionMenu();
        cm.setVisible(true);

    }//GEN-LAST:event_jbtnMenuActionPerformed

    private void jbtnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDashboardActionPerformed
        this.dispose();
        jfprincipal app1 = new jfprincipal();
        app1.setVisible(true);
    }//GEN-LAST:event_jbtnDashboardActionPerformed

    private void jbtnProductoUnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnProductoUnoMouseEntered
        
        jbtnProductoUno.setBackground(new Color(193, 193, 193));
        
    }//GEN-LAST:event_jbtnProductoUnoMouseEntered

    private void jbtnProductoUnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnProductoUnoMouseExited
        jbtnProductoUno.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jbtnProductoUnoMouseExited

    private void jbtnProductoDosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnProductoDosMouseEntered
        jbtnProductoDos.setBackground(new Color(193, 193, 193));
    }//GEN-LAST:event_jbtnProductoDosMouseEntered

    private void jbtnProductoDosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnProductoDosMouseExited
        jbtnProductoDos.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jbtnProductoDosMouseExited

    private void jbtnProductoTresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnProductoTresMouseEntered
        jbtnProductoTres.setBackground(new Color(193, 193, 193));
    }//GEN-LAST:event_jbtnProductoTresMouseEntered

    private void jbtnProductoTresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnProductoTresMouseExited
        jbtnProductoTres.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jbtnProductoTresMouseExited

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
        
        this.dispose();
            jfLoginOrCreateAcount app = new jfLoginOrCreateAcount();
                app.setVisible(true);
        
    }//GEN-LAST:event_jbtnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfprincipal().setVisible(true);
            }
        });
    }

    public void setImagesToComponents(){
        
        //jbtnDashboard.setPressedIcon(); //para cuando se precione un botón.
        this.setIconImage(new ImageIcon(getClass().getResource("/00_jf_principal/idm.png")).getImage());
                jbtnProductoUno.setIcon(setIconoBtn("/01_lo_mas_comprado/01.png",jbtnProductoUno));
                    jbtnProductoDos.setIcon(setIconoBtn("/01_lo_mas_comprado/02.png",jbtnProductoDos));
                        jbtnProductoTres.setIcon(setIconoBtn("/01_lo_mas_comprado/03.png",jbtnProductoTres));
                            jbtnMenu1.setIcon(setIconoBtn("/00_jf_principal/iconoMenu.png",jbtnMenu1));
                                jbtnLogin.setIcon(setIconoBtn("/00_jf_principal/loginIcon.png",jbtnLogin));
    }
    
    public Icon setIconoBtn(String url, JButton btn){
    
        //jbtnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizza.png")));
        ImageIcon imgIcon = new ImageIcon(getClass().getResource(url));
            int widthBtn = btn.getWidth();
                int heightBtn = btn.getHeight();
        
                    ImageIcon iconoBtn = new ImageIcon(imgIcon.getImage().getScaledInstance(widthBtn, heightBtn, Image.SCALE_DEFAULT));
                        return iconoBtn;
    }
    
     public void cerrar(){
    
        try {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e){ //WindowEvent: import java.awt.event.WindowEvent;
                      confirmarCerrarVentana();
                }
            });
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    
    public void confirmarCerrarVentana(){
        Icon question;
        question = new ImageIcon(getClass().getResource("/00_jf_principal/question.png"));
        
        int valor = JOptionPane.showConfirmDialog(null, "¿REALMENTE QUIERES CERRAR LA VENTANA?", "ATENCIÓN", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE,question);
        if(valor == JOptionPane.YES_OPTION){
            this.dispose(); 
        }else{
            this.setVisible(true);
        }  
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnDashboard1;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JButton jbtnMenu1;
    private javax.swing.JButton jbtnProductoDos;
    private javax.swing.JButton jbtnProductoTres;
    private javax.swing.JButton jbtnProductoUno;
    private javax.swing.JPanel jpDown;
    private javax.swing.JPanel jpUpMenuOptions;
    // End of variables declaration//GEN-END:variables
}
