/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.proyectofinal.frames;

import com.proyectofinal.clases.empleado;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Manuel
 */
public final class jfRegistrarActualizarEliminar extends javax.swing.JFrame {

    empleado emp = null;
    
    /**
     * Creates new form jfRegistrarActualizarEliminar
     */
    public jfRegistrarActualizarEliminar() {
        initComponents();
    }

    public jfRegistrarActualizarEliminar(empleado emp){
        this.emp = emp;
            initComponents();
                setImgComponents();
                    cerrar();
    }
    
        class jPanelGradient extends JPanel{
        
        @Override
        protected void paintComponent(Graphics g){
            Graphics2D g2d = (Graphics2D) g;
                int width = getWidth();
                int height = getHeight();
                    Color colorUno = new Color(0, 120, 174);
                    Color colorDos = new Color(185, 238, 226);
                        GradientPaint gp = new GradientPaint(0,0,colorUno,180,height,colorDos);
                            g2d.setPaint(gp);
                            g2d.fillRect(0, 0, width, height);
                
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelCategorias = new jPanelGradient();
        jbtnMesas = new javax.swing.JButton();
        jbtnClientes = new javax.swing.JButton();
        jbtnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DOMINO´S PIZZA");

        jpanelCategorias.setMaximumSize(new java.awt.Dimension(900, 500));
        jpanelCategorias.setMinimumSize(new java.awt.Dimension(900, 500));

        jbtnMesas.setBackground(new java.awt.Color(255, 255, 255));
        jbtnMesas.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jbtnMesas.setForeground(new java.awt.Color(0, 120, 174));
        jbtnMesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/06_mesasClientes/mesas.png"))); // NOI18N
        jbtnMesas.setText("                MESAS");
        jbtnMesas.setBorderPainted(false);
        jbtnMesas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnMesas.setFocusPainted(false);
        jbtnMesas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jbtnMesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnMesasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnMesasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnMesasMouseExited(evt);
            }
        });
        jbtnMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMesasActionPerformed(evt);
            }
        });

        jbtnClientes.setBackground(new java.awt.Color(255, 255, 255));
        jbtnClientes.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jbtnClientes.setForeground(new java.awt.Color(0, 120, 174));
        jbtnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/06_mesasClientes/cliente.png"))); // NOI18N
        jbtnClientes.setText("            CLIENTES");
        jbtnClientes.setBorderPainted(false);
        jbtnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnClientes.setFocusPainted(false);
        jbtnClientes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jbtnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnClientesMouseExited(evt);
            }
        });
        jbtnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClientesActionPerformed(evt);
            }
        });

        jbtnVolver.setBackground(new java.awt.Color(148, 214, 216));
        jbtnVolver.setBorder(null);
        jbtnVolver.setBorderPainted(false);
        jbtnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnVolver.setFocusPainted(false);
        jbtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelCategoriasLayout = new javax.swing.GroupLayout(jpanelCategorias);
        jpanelCategorias.setLayout(jpanelCategoriasLayout);
        jpanelCategoriasLayout.setHorizontalGroup(
            jpanelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelCategoriasLayout.createSequentialGroup()
                .addGroup(jpanelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelCategoriasLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(jpanelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpanelCategoriasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jpanelCategoriasLayout.setVerticalGroup(
            jpanelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelCategoriasLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jbtnMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jbtnClientes)
                .addGap(51, 51, 51)
                .addComponent(jbtnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnClientesMouseEntered
        jbtnClientes.setBackground(new Color(0, 120, 174));
        jbtnClientes.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_jbtnClientesMouseEntered

    private void jbtnClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnClientesMouseExited
        jbtnClientes.setBackground(new Color(255,255,255));
        jbtnClientes.setForeground(new java.awt.Color(0, 120, 174));
    }//GEN-LAST:event_jbtnClientesMouseExited

    private void jbtnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClientesActionPerformed
        this.dispose();
            jfClientes clientesjf = new jfClientes(emp);
                 clientesjf.setVisible(true); 
    }//GEN-LAST:event_jbtnClientesActionPerformed

    private void jbtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVolverActionPerformed
        jfprincipal app1 = new jfprincipal(emp);
            this.dispose();
                app1.setVisible(true);
    }//GEN-LAST:event_jbtnVolverActionPerformed

    private void jbtnMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMesasActionPerformed
        this.dispose();
        jfMesas mesasRegistros = new jfMesas(emp);
        mesasRegistros.setVisible(true);
    }//GEN-LAST:event_jbtnMesasActionPerformed

    private void jbtnMesasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnMesasMouseExited
        jbtnMesas.setBackground(new Color(255,255,255));
        jbtnMesas.setForeground(new java.awt.Color(0, 120, 174));
    }//GEN-LAST:event_jbtnMesasMouseExited

    private void jbtnMesasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnMesasMouseEntered
        jbtnMesas.setBackground(new Color(0, 120, 174));
        jbtnMesas.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_jbtnMesasMouseEntered

    private void jbtnMesasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnMesasMouseClicked

    }//GEN-LAST:event_jbtnMesasMouseClicked

     public void cerrar(){
    
        try {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e){ //WindowEvent: import java.awt.event.WindowEvent;
                      confirmarCerrarVentana();
                }
            });
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    
    public void confirmarCerrarVentana(){
        Icon question;
        question = new ImageIcon(getClass().getResource("/00_jf_principal/question.png"));
        
        int valor = JOptionPane.showConfirmDialog(null, "¿REALMENTE QUIERES CERRAR LA VENTANA?", "ATENCIÓN", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE,question);
        if(valor == JOptionPane.YES_OPTION){
            jfprincipal principalframe = new jfprincipal(emp);
                this.dispose();
                    principalframe.setVisible(true);
        }else{
            this.setVisible(true);
        }  
    }
    
    public void setImgComponents(){
        this.setIconImage(new ImageIcon(getClass().getResource("/00_jf_principal/idm.png")).getImage());
            jbtnVolver.setIcon(setIconoBtn("/06_mesasClientes/05.png",jbtnVolver));
    }
    
    public Icon setIconoBtn(String url, JButton btn){
    
        //jbtnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizza.png")));
        ImageIcon imgIcon = new ImageIcon(getClass().getResource(url));
            int widthBtn = btn.getWidth();
                int heightBtn = btn.getHeight();
        
                    ImageIcon iconoBtn = new ImageIcon(imgIcon.getImage().getScaledInstance(widthBtn, heightBtn, Image.SCALE_DEFAULT));
                        return iconoBtn;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfRegistrarActualizarEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfRegistrarActualizarEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfRegistrarActualizarEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfRegistrarActualizarEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfRegistrarActualizarEliminar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnClientes;
    private javax.swing.JButton jbtnMesas;
    private javax.swing.JButton jbtnVolver;
    private javax.swing.JPanel jpanelCategorias;
    // End of variables declaration//GEN-END:variables
}
