/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.proyectofinal.frames;

import com.proyectofinal.clases.empleado;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Manuel
 */
public final class perfilDelUsuario extends javax.swing.JFrame {

    empleado emp = null;
    
    /**
     * Creates new form perfilDelUsuario
     */
    public perfilDelUsuario() {
        initComponents();
            cerrar();
    }

     public perfilDelUsuario(empleado emp) {
            this.emp = emp;
                initComponents();
                    setDatosInLabels();
                        setImagesToComponents();
                            cerrar();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelPerfilUsuario = new jPanelGradient();
        jbtnVolver = new javax.swing.JButton();
        jpEncabezado = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jpanelDatosATraer = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jpanelDatosATraer1 = new jPanelGradient2();
        jlblUsuarioPerfil = new javax.swing.JLabel();
        jlblNombrePerfil = new javax.swing.JLabel();
        jlblApellidoPerfil = new javax.swing.JLabel();
        jlblCorreoPerfil = new javax.swing.JLabel();
        jlblTipoPerfil = new javax.swing.JLabel();
        jbtnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DOMINO´S PIZZA");
        setMinimumSize(new java.awt.Dimension(900, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelPerfilUsuario.setMaximumSize(new java.awt.Dimension(900, 500));
        jpanelPerfilUsuario.setMinimumSize(new java.awt.Dimension(900, 500));
        jpanelPerfilUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnVolver.setBackground(new java.awt.Color(161, 223, 219));
        jbtnVolver.setBorder(null);
        jbtnVolver.setBorderPainted(false);
        jbtnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnVolver.setFocusPainted(false);
        jbtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVolverActionPerformed(evt);
            }
        });
        jpanelPerfilUsuario.add(jbtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 80, 75));

        jpEncabezado.setBackground(new java.awt.Color(0, 100, 145));

        jLabel3.setBackground(new java.awt.Color(0, 100, 145));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DATOS DEL USUARIO");

        javax.swing.GroupLayout jpEncabezadoLayout = new javax.swing.GroupLayout(jpEncabezado);
        jpEncabezado.setLayout(jpEncabezadoLayout);
        jpEncabezadoLayout.setHorizontalGroup(
            jpEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEncabezadoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addContainerGap(632, Short.MAX_VALUE))
        );
        jpEncabezadoLayout.setVerticalGroup(
            jpEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEncabezadoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jpanelPerfilUsuario.add(jpEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 70));

        jpanelDatosATraer.setBackground(new java.awt.Color(0, 100, 145));

        jLabel4.setBackground(new java.awt.Color(0, 100, 145));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("USUARIO");

        jLabel5.setBackground(new java.awt.Color(0, 100, 145));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NOMBRE");

        jLabel6.setBackground(new java.awt.Color(0, 100, 145));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CORREO");

        jLabel7.setBackground(new java.awt.Color(0, 100, 145));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("APELLIDO");

        jLabel8.setBackground(new java.awt.Color(0, 100, 145));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TIPO");

        javax.swing.GroupLayout jpanelDatosATraerLayout = new javax.swing.GroupLayout(jpanelDatosATraer);
        jpanelDatosATraer.setLayout(jpanelDatosATraerLayout);
        jpanelDatosATraerLayout.setHorizontalGroup(
            jpanelDatosATraerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelDatosATraerLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jpanelDatosATraerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jpanelDatosATraerLayout.setVerticalGroup(
            jpanelDatosATraerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelDatosATraerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jpanelPerfilUsuario.add(jpanelDatosATraer, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 150, 250));

        jlblUsuarioPerfil.setBackground(new java.awt.Color(51, 153, 255));
        jlblUsuarioPerfil.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jlblUsuarioPerfil.setForeground(new java.awt.Color(51, 51, 51));
        jlblUsuarioPerfil.setText(" ");

        jlblNombrePerfil.setBackground(new java.awt.Color(51, 153, 255));
        jlblNombrePerfil.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jlblNombrePerfil.setForeground(new java.awt.Color(51, 51, 51));
        jlblNombrePerfil.setText(" ");

        jlblApellidoPerfil.setBackground(new java.awt.Color(51, 153, 255));
        jlblApellidoPerfil.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jlblApellidoPerfil.setForeground(new java.awt.Color(51, 51, 51));
        jlblApellidoPerfil.setText(" ");

        jlblCorreoPerfil.setBackground(new java.awt.Color(51, 153, 255));
        jlblCorreoPerfil.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jlblCorreoPerfil.setForeground(new java.awt.Color(51, 51, 51));
        jlblCorreoPerfil.setText(" ");

        jlblTipoPerfil.setBackground(new java.awt.Color(51, 153, 255));
        jlblTipoPerfil.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jlblTipoPerfil.setForeground(new java.awt.Color(51, 51, 51));
        jlblTipoPerfil.setText(" ");

        javax.swing.GroupLayout jpanelDatosATraer1Layout = new javax.swing.GroupLayout(jpanelDatosATraer1);
        jpanelDatosATraer1.setLayout(jpanelDatosATraer1Layout);
        jpanelDatosATraer1Layout.setHorizontalGroup(
            jpanelDatosATraer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelDatosATraer1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jpanelDatosATraer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblUsuarioPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                    .addComponent(jlblNombrePerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblApellidoPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblCorreoPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblTipoPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jpanelDatosATraer1Layout.setVerticalGroup(
            jpanelDatosATraer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelDatosATraer1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jlblUsuarioPerfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblNombrePerfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblApellidoPerfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblCorreoPerfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblTipoPerfil)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jpanelPerfilUsuario.add(jpanelDatosATraer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 330, 250));

        jbtnCerrarSesion.setBackground(new java.awt.Color(0, 120, 174));
        jbtnCerrarSesion.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jbtnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        jbtnCerrarSesion.setText("CERRAR SESIÓN");
        jbtnCerrarSesion.setBorder(null);
        jbtnCerrarSesion.setBorderPainted(false);
        jbtnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnCerrarSesion.setFocusPainted(false);
        jbtnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnCerrarSesionMouseExited(evt);
            }
        });
        jbtnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCerrarSesionActionPerformed(evt);
            }
        });
        jpanelPerfilUsuario.add(jbtnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, -1, -1));

        getContentPane().add(jpanelPerfilUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    class jPanelGradient extends JPanel{  
            @Override
            protected void paintComponent(Graphics g){
                Graphics2D g2d = (Graphics2D) g;
                    int width = getWidth();
                    int height = getHeight();                    
                        Color colorUno = new Color(0, 120, 174);
                        Color colorDos = new Color(185, 238, 226);
                            GradientPaint gp = new GradientPaint(0,0,colorUno,180,height,colorDos);
                                g2d.setPaint(gp);
                                g2d.fillRect(0, 0, width, height);
            }
        }
    
    class jPanelGradient2 extends JPanel{  
            @Override
            protected void paintComponent(Graphics g){
                Graphics2D g2d = (Graphics2D) g;
                    int width = getWidth();
                    int height = getHeight();                
                        Color colorUno = new Color(255,255,255);
                        Color colorDos = new Color(187,187,187);
                            GradientPaint gp = new GradientPaint(0,0,colorUno,180,height,colorDos);
                                g2d.setPaint(gp);
                                g2d.fillRect(0, 0, width, height);
            }
        }
    
    private void jbtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVolverActionPerformed
        backFromThis();
    }//GEN-LAST:event_jbtnVolverActionPerformed

    private void jbtnCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnCerrarSesionMouseEntered
        jbtnCerrarSesion.setBackground(new Color(0,120,174));
        jbtnCerrarSesion.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_jbtnCerrarSesionMouseEntered

    private void jbtnCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnCerrarSesionMouseExited
        jbtnCerrarSesion.setBackground(new Color(255,255,255));
        jbtnCerrarSesion.setForeground(new Color(0,120,174));
    }//GEN-LAST:event_jbtnCerrarSesionMouseExited

    private void jbtnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCerrarSesionActionPerformed
        this.dispose();
            jfLoginOrCreateAcount loca = new jfLoginOrCreateAcount();
                loca.setVisible(true);
    }//GEN-LAST:event_jbtnCerrarSesionActionPerformed

    public void backFromThis(){
        this.dispose();
            jfprincipal principal = new jfprincipal(emp);
                principal.setVisible(true); 
    }
    
    public void setDatosInLabels(){
        
        jlblUsuarioPerfil.setText(emp.getUsuario());
        jlblNombrePerfil.setText(emp.getNombre());
        jlblApellidoPerfil.setText(emp.getApellido());
        jlblCorreoPerfil.setText(emp.getCorreo());
        jlblTipoPerfil.setText(emp.getTipoEmpleado());
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(perfilDelUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(perfilDelUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(perfilDelUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(perfilDelUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new perfilDelUsuario().setVisible(true);
            }
        });
    }
    
    public void setImagesToComponents(){
        
        this.setIconImage(new ImageIcon(getClass().getResource("/00_jf_principal/idm.png")).getImage());
            jbtnVolver.setIcon(setIconoBtn("/02_clasificacion_menu/05.png", jbtnVolver));
    }
    
    public Icon setIconoBtn(String url, JButton btn){
    
        //jbtnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizza.png")));
        ImageIcon imgIcon = new ImageIcon(getClass().getResource(url));
            int widthBtn = btn.getWidth();
                int heightBtn = btn.getHeight();
        
                    ImageIcon iconoBtn = new ImageIcon(imgIcon.getImage().getScaledInstance(widthBtn, heightBtn, Image.SCALE_DEFAULT));
                        return iconoBtn;
    }

     public void cerrar(){
    
        try {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e){ //WindowEvent: import java.awt.event.WindowEvent;
                      confirmarCerrarVentana();
                }
            });
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    
    public void confirmarCerrarVentana(){
        Icon question;
        question = new ImageIcon(getClass().getResource("/00_jf_principal/question.png"));
        
        int valor = JOptionPane.showConfirmDialog(null, "¿REALMENTE QUIERES CERRAR LA VENTANA?", "ATENCIÓN", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE,question);
        if(valor == JOptionPane.YES_OPTION){
            jfprincipal prin = new jfprincipal(emp);
                this.dispose(); 
                    prin.setVisible(true);
        }else{
            this.setVisible(true);
        }  
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jbtnCerrarSesion;
    private javax.swing.JButton jbtnVolver;
    private javax.swing.JLabel jlblApellidoPerfil;
    private javax.swing.JLabel jlblCorreoPerfil;
    private javax.swing.JLabel jlblNombrePerfil;
    private javax.swing.JLabel jlblTipoPerfil;
    private javax.swing.JLabel jlblUsuarioPerfil;
    private javax.swing.JPanel jpEncabezado;
    private javax.swing.JPanel jpanelDatosATraer;
    private javax.swing.JPanel jpanelDatosATraer1;
    private javax.swing.JPanel jpanelPerfilUsuario;
    // End of variables declaration//GEN-END:variables
}
